### ISSUE TITLE
sabnzbd script error

### ISSUE THREAD

**Issue by ShoGinn** [nosmokingbandit/Watcher3#10]
SABnzbd: Version:	2.0.0RC2 [afd1b19]
Python 3.5.2
--proxmox container ubuntu 16.04

I updated the script to the new watcher3 version and this is the error i get in sabnzbd

```
Traceback (most recent call last):
  File "/home/sabnzbd/scripts/watcher.py", line 47, in <module>
    slots = json.loads(response)['history']['slots']
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by nosmokingbandit** [comment]
6d25fb2258ed52047d9f9bf7c773abcf6802f5b8 should take care of it. Remember to copy the script again after applying the update.

**Comment by ShoGinn** [comment]
Unfortunately it still does not work:

```
Traceback (most recent call last):
  File "/home/sabnzbd/scripts/watcher.py", line 69, in <module>
    response = json.loads(urllib.request.urlopen(request, timeout=600).read().decode('utf-8'))
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by nosmokingbandit** [comment]
Something went wrong on the Watcher side this time. Look in your logs for a section that starts with this:

```
#################################
Post-processing request received.
#################################
```

Copy that and everything below it and email it to me watchernzb@gmail.com

**Comment by ShoGinn** [comment]
not a big deal to post here ;) i'll sanitize

```
INFO 2017-04-05 19:22:52,181 core.postprocessing.POST: #################################
INFO 2017-04-05 19:22:52,181 core.postprocessing.POST: Post-processing request received.
INFO 2017-04-05 19:22:52,181 core.postprocessing.POST: #################################
INFO 2017-04-05 19:22:52,181 core.postprocessing.get_movie_file: Finding movie file.
INFO 2017-04-05 19:22:52,185 core.postprocessing.get_movie_file: Post-processing file /mnt/media/Downloads/sabnzbd/complete/movies/<super cool stuff.mkv>.
INFO 2017-04-05 19:22:52,185 core.postprocessing.POST: Parsing release name for information.
INFO 2017-04-05 19:22:52,185 core.library.parse_filename: Parsing /mnt/media/Downloads/sabnzbd/complete/movies/<super cool stuff.mkv> for movie information.
INFO 2017-04-05 19:22:52,188 core.library.parse_filename: Found {'container': 'mkv', 'season': 0, 'episode': 42, 'title': '<title>'} in filename.
INFO 2017-04-05 19:22:52,188 core.postprocessing.POST: Gathering release information.
INFO 2017-04-05 19:22:52,188 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-04-05 19:22:52,188 core.sqldb.get_single_search_result: Retrieving search result details for http://mediaserver.localdomain:5075/nzbhydra/getnzb?apikey=<api>.
INFO 2017-04-05 19:22:52,190 core.postprocessing.get_movie_info: Searchresult found by guid.
INFO 2017-04-05 19:22:52,190 core.postprocessing.get_movie_info: Searching local database by imdbid.
INFO 2017-04-05 19:22:52,190 core.sqldb.get_movie_details: Retrieving details for <imdb id>.
INFO 2017-04-05 19:22:52,190 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
INFO 2017-04-05 19:22:52,190 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-04-05 19:22:52,190 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-04-05 19:22:52,190 core.library.searchresults: Marking guid http//mediaserver.localdomain5075/nzbhydra/getnzbapikey=<api> as Finished.
INFO 2017-04-05 19:22:52,191 core.library.searchresults: Guid http//mediaserver.localdomain5075/nzbhydra/getnzbapikey=<api> not found in SEARCHRESULTS, attempting to create entry.
ERROR 2017-04-05 19:22:52,191 cherrypy.error.139640182457624.error: [05/Apr/2017:19:22:52] HTTP 
Traceback (most recent call last):
  File "/opt/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/core/postprocessing.py", line 102, in POST
    response = self.complete(data)
  File "/opt/watcher/core/postprocessing.py", line 364, in complete
    if self.update.searchresults(data['guid'], 'Finished', movie_info=data):
  File "/opt/watcher/core/library.py", line 639, in searchresults
    search_result = searchresults.generate_phony(movie_info)
AttributeError: module 'core.searchresults' has no attribute 'generate_phony'
INFO 2017-04-05 19:22:52,192 cherrypy.error.139640182457624.error: [05/Apr/2017:19:22:52] HTTP 
Request Headers:
  CONNECTION: close
  Remote-Addr: 127.0.0.1
  USER-AGENT: Mozilla/5.0
  HOST: localhost:9090
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 352
  ACCEPT-ENCODING: identity

```

**Comment by nosmokingbandit** [comment]
No this was just me being dumb. I tend to get distracted easily and work on too many things and once and lose my place.

39f4ea1ad616e1f72e94740adfcccdb4814c603a should take care of it.

**Comment by ShoGinn** [comment]
Still more errors ;)
-Same SABnzbd error:

```
Traceback (most recent call last):
  File "/home/sabnzbd/scripts/watcher.py", line 69, in <module>
    response = json.loads(urllib.request.urlopen(request, timeout=600).read().decode('utf-8'))
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

Different log error


```
INFO 2017-04-06 23:17:57,968 core.postprocessing.POST: #################################
INFO 2017-04-06 23:17:57,968 core.postprocessing.POST: Post-processing request received.
INFO 2017-04-06 23:17:57,968 core.postprocessing.POST: #################################
INFO 2017-04-06 23:17:57,968 core.postprocessing.get_movie_file: Finding movie file.
INFO 2017-04-06 23:17:57,972 core.postprocessing.get_movie_file: Post-processing file <file.mkv>.
INFO 2017-04-06 23:17:57,972 core.postprocessing.POST: Parsing release name for information.
INFO 2017-04-06 23:17:57,972 core.library.parse_filename: Parsing <file.mkv> for movie information.
INFO 2017-04-06 23:17:57,975 core.library.parse_filename: Found {'title': '<title>', 'container': 'mkv'} in filename.
INFO 2017-04-06 23:17:57,975 core.postprocessing.POST: Gathering release information.
INFO 2017-04-06 23:17:57,975 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-04-06 23:17:57,975 core.sqldb.get_single_search_result: Retrieving search result details for http://mediaserver.localdomain:5075/nzbhydra/getnzb?apikey=<api>.
INFO 2017-04-06 23:17:57,977 core.postprocessing.get_movie_info: Searchresult found by guid.
INFO 2017-04-06 23:17:57,977 core.postprocessing.get_movie_info: Searching local database by imdbid.
INFO 2017-04-06 23:17:57,977 core.sqldb.get_movie_details: Retrieving details for <imdbid>.
INFO 2017-04-06 23:17:57,978 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
INFO 2017-04-06 23:17:57,978 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-04-06 23:17:57,978 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-04-06 23:17:57,978 core.library.searchresults: Marking guid http//mediaserver.localdomain5075/nzbhydra/getnzbapikey=<api> as Finished.
INFO 2017-04-06 23:17:57,979 core.library.searchresults: Guid http//mediaserver.localdomain5075/nzbhydra/getnzbapikey=<api> not found in SEARCHRESULTS, attempting to create entry.
INFO 2017-04-06 23:17:57,979 cherrypy.error.140378697032536.error: [06/Apr/2017:23:17:57] HTTP
Request Headers:
  ACCEPT-ENCODING: identity
  Remote-Addr: 127.0.0.1
  USER-AGENT: Mozilla/5.0
  CONNECTION: close
  Content-Type: application/x-www-form-urlencoded
  HOST: localhost:9090
  Content-Length: 370
ERROR 2017-04-06 23:17:57,979 cherrypy.error.140378697032536.error: [06/Apr/2017:23:17:57] HTTP
Traceback (most recent call last):
  File "/opt/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/core/postprocessing.py", line 102, in POST
    response = self.complete(data)
  File "/opt/watcher/core/postprocessing.py", line 364, in complete
    if self.update.searchresults(data['guid'], 'Finished', movie_info=data):
  File "/opt/watcher/core/library.py", line 639, in searchresults
    search_result = searchresults.generate_simulacrum(movie_info)
TypeError: 'staticmethod' object is not callable

```

**Comment by nosmokingbandit** [comment]
Didn't mean to close this, Git sometimes automatically closes issues when referenced in a commit message.

Anyway, 3e63e1f6270dca338b16ca47b86b6e6d7a235689 should fix this.

**Comment by DrMarf** [comment]
On a clean DB it works fine for me. On an existing DB after I do a pull it appears the DB is missing a column on a table. Would you like the full log as well?

`table SEARCHRESULTS has no column named releasegroup`

**Comment by nosmokingbandit** [comment]
I'm not sure why it was even trying to write the release group. I just need the traceback from that exception to know exactly where it is happening.

**Comment by DrMarf** [comment]
I am totally fine with starting clean. It was probably something I did. I am sorry and I don't mean to be a pain. But here it is in case it helps someone else. Hope I didn't scrub it too much.
Thanks for all your work.

INFO 2017-04-07 15:28:50,123 core.postprocessing.POST: #################################
INFO 2017-04-07 15:28:50,123 core.postprocessing.POST: Post-processing request received.
INFO 2017-04-07 15:28:50,124 core.postprocessing.POST: #################################
INFO 2017-04-07 15:28:50,124 core.postprocessing.get_movie_file: Finding movie file.
INFO 2017-04-07 15:28:50,124 core.postprocessing.get_movie_file: Post-processing file /share/Download/nzbget/dst/Watcher/[removed]/88a8b6fd2a0d41a89ace94d11f5b97fc.mkv.
INFO 2017-04-07 15:28:50,124 core.postprocessing.POST: Parsing release name for information.
INFO 2017-04-07 15:28:50,125 core.library.parse_filename: Parsing /share/Download/nzbget/dst/Watcher/[removed]/88a8b6fd2a0d41a89ace94d11f5b97fc.mkv for movie information.
INFO 2017-04-07 15:28:50,164 core.library.parse_filename: Found {'episode': 94, 'container': 'mkv', 'title': '88a8b6fd2a0d41a89ac', 'episodeName': '11f5b97fc'} in filename.
INFO 2017-04-07 15:28:50,165 core.postprocessing.POST: Gathering release information.
INFO 2017-04-07 15:28:50,165 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-04-07 15:28:50,165 core.sqldb.get_single_search_result: Retrieving search result details for http://localhost:5075/getnzb?apikey=[removed].
INFO 2017-04-07 15:28:50,169 core.postprocessing.get_movie_info: Searchresult found by guid.
INFO 2017-04-07 15:28:50,170 core.postprocessing.get_movie_info: Searching local database by imdbid.
INFO 2017-04-07 15:28:50,170 core.sqldb.get_movie_details: Retrieving details for [removed].
INFO 2017-04-07 15:28:50,172 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
INFO 2017-04-07 15:28:50,173 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-04-07 15:28:50,173 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-04-07 15:28:50,173 core.library.searchresults: Marking guid [removed] as Finished.
INFO 2017-04-07 15:28:50,177 core.library.searchresults: Guid [removed] not found in SEARCHRESULTS, attempting to create entry.
INFO 2017-04-07 15:28:50,177 core.searchresults.score: Scoring 1 results.
INFO 2017-04-07 15:28:50,178 core.searchresults.retention_check: Checking retention.
INFO 2017-04-07 15:28:50,178 core.searchresults.retention_check: Keeping 1 results.
INFO 2017-04-07 15:28:50,178 core.searchresults.seed_check: Checking torrent seeds.
INFO 2017-04-07 15:28:50,178 core.searchresults.seed_check: Keeping 1 results.
INFO 2017-04-07 15:28:50,178 core.searchresults.score_sources: Filtering resolution and size requirements.
DEBUG 2017-04-07 15:28:50,179 core.searchresults.score_sources: [removed] matches source BluRay-720P, checking size.
DEBUG 2017-04-07 15:28:50,179 core.searchresults.score_sources: [removed] is an import, skipping size check.
INFO 2017-04-07 15:28:50,179 core.searchresults.score_sources: Keeping 1 results.
INFO 2017-04-07 15:28:50,179 core.searchresults.fuzzy_title: Checking title match.
INFO 2017-04-07 15:28:50,179 core.searchresults.fuzzy_title: Keeping 1 results.
INFO 2017-04-07 15:28:50,179 core.searchresults.score_preferred: Scoring Preferred Words.
INFO 2017-04-07 15:28:50,180 core.searchresults.score: Finished scoring search results.
INFO 2017-04-07 15:28:50,180 core.sqldb.write: Writing data to SEARCHRESULTS.
ERROR 2017-04-07 15:28:50,181 core.sqldb.execute: SQL Database Query: ['INSERT INTO SEARCHRESULTS ( status, info_link, pubdate, title, imdbid, torrentfile, indexer, date_found, score, type, downloadid, guid, resolution, size, releasegroup, freeleech ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )', ['Finished', '#', None, '[removed]', '[removed]', None, 'Post-Processing Import', '2017-04-07', 580, 'import', None, '[removed]', 'BluRay-720P', 4096, '', 0]].
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table SEARCHRESULTS has no column named releasegroup

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/sqldb.py", line 113, in execute
    result = self.engine.execute(*command)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table SEARCHRESULTS has no column named releasegroup [SQL: 'INSERT INTO SEARCHRESULTS ( status, info_link, pubdate, title, imdbid, torrentfile, indexer, date_found, score, type, downloadid, guid, resolution, size, releasegroup, freeleech ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )'] [parameters: ('Finished', '#', None, '[removed]', '[removed]', None, 'Post-Processing Import', '2017-04-07', 580, 'import', None, '[removed]', 'BluRay-720P', 4096, '', 0)]
ERROR 2017-04-07 15:28:50,185 core.sqldb.execute: SQL Databse Query: ['INSERT INTO SEARCHRESULTS ( status, info_link, pubdate, title, imdbid, torrentfile, indexer, date_found, score, type, downloadid, guid, resolution, size, releasegroup, freeleech ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )', ['Finished', '#', None, '[removed]', '[removed]', None, 'Post-Processing Import', '2017-04-07', 580, 'import', None, '[removed]', 'BluRay-720P', 4096, '', 0]].
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table SEARCHRESULTS has no column named releasegroup

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/sqldb.py", line 113, in execute
    result = self.engine.execute(*command)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table SEARCHRESULTS has no column named releasegroup [SQL: 'INSERT INTO SEARCHRESULTS ( status, info_link, pubdate, title, imdbid, torrentfile, indexer, date_found, score, type, downloadid, guid, resolution, size, releasegroup, freeleech ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )'] [parameters: ('Finished', '#', None, '[removed]', '[removed]', None, 'Post-Processing Import', '2017-04-07', 580, 'import', None, '[removed]', 'BluRay-720P', 4096, '', 0)]
ERROR 2017-04-07 15:28:50,187 cherrypy.error.139673253398064.error: [07/Apr/2017:15:28:50] HTTP 
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table SEARCHRESULTS has no column named releasegroup

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/postprocessing.py", line 101, in POST
    response = self.complete(data)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/postprocessing.py", line 363, in complete
    if self.update.searchresults(data['guid'], 'Finished', movie_info=data):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/library.py", line 646, in searchresults
    if self.sql.write('SEARCHRESULTS', search_result):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/sqldb.py", line 149, in write
    if self.execute(command):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/sqldb.py", line 113, in execute
    result = self.engine.execute(*command)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table SEARCHRESULTS has no column named releasegroup [SQL: 'INSERT INTO SEARCHRESULTS ( status, info_link, pubdate, title, imdbid, torrentfile, indexer, date_found, score, type, downloadid, guid, resolution, size, releasegroup, freeleech ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )'] [parameters: ('Finished', '#', None, '[removed]', '[removed]', None, 'Post-Processing Import', '2017-04-07', 580, 'import', None, 'http_//localhost_5075/getnzb_apikey=[removed]&searchresultid=7797c0290fec6de4db890c568d0679df054ea9fe', 'BluRay-720P', 4096, '', 0)]
INFO 2017-04-07 15:28:50,192 cherrypy.error.139673253398064.error: [07/Apr/2017:15:28:50] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  ACCEPT-ENCODING: identity
  HOST: localhost:9090
  CONNECTION: close
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 307

**Comment by nosmokingbandit** [comment]
5adcb61f6e4ad023a7f561f3408b2bbdca10f68f should fix that.

**Comment by ShoGinn** [comment]
Seems it's working for me keep up the good work!
