### ISSUE TITLE
error sending to sabnzbd

### ISSUE THREAD

**Issue by phynias** [nosmokingbandit/Watcher3#101]
connection test works fine..

INFO 2017-07-22 22:21:59,222 core.snatcher.grab_all: Other People status is Found. Running automatic snatcher.
DEBUG 2017-07-22 22:21:59,222 core.sqldb.get_search_results: Retrieving Search Results for tt4158876.
INFO 2017-07-22 22:21:59,222 core.snatcher.best_release: Earliest found result for tt4158876 is 2017-07-22 00:00:00, waiting 1 days to grab best result.
INFO 2017-07-22 22:21:59,222 core.snatcher.best_release: Other People released 45.142857142857146 weeks ago, skipping wait and grabbing immediately.
INFO 2017-07-22 22:21:59,223 core.snatcher.best_release: Selecting best result for tt4158876
INFO 2017-07-22 22:21:59,223 core.snatcher.snatch_nzb: Sending nzb to Sabnzbd.
ERROR 2017-07-22 22:21:59,224 core.downloaders.sabnzbd.add_nzb: Unable to send NZB to Sabnzbd.
Traceback (most recent call last):
  File "/usr/local/Watcher3/core/downloaders/sabnzbd.py", line 76, in add_nzb
    response = json.loads(Url.open(url).text)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by phynias** [comment]
nm, problem was the sab api only listened on https.
