### ISSUE TITLE
500 error from postproc script

### ISSUE THREAD

**Issue by phynias** [nosmokingbandit/Watcher3#106]
the post proc script for sabnzbd was getting a 500 error from watcher in the log i see this.

INFO 2017-07-26 21:25:37,693 core.searchresults.score: Scoring 1 results.
INFO 2017-07-26 21:25:37,694 core.searchresults.retention_check: Checking retention.
INFO 2017-07-26 21:25:37,694 core.searchresults.retention_check: Keeping 1 results.
INFO 2017-07-26 21:25:37,694 core.searchresults.seed_check: Checking torrent seeds.
INFO 2017-07-26 21:25:37,694 core.searchresults.seed_check: Keeping 1 results.
INFO 2017-07-26 21:25:37,694 core.searchresults.score_sources: Filtering resolution and size requirements.
INFO 2017-07-26 21:25:37,694 core.searchresults.score_sources: Keeping 0 results.
INFO 2017-07-26 21:25:37,694 core.searchresults.fuzzy_title: Checking title match.
INFO 2017-07-26 21:25:37,694 core.searchresults.fuzzy_title: Keeping 0 results.
INFO 2017-07-26 21:25:37,694 core.searchresults.score_preferred: Scoring Preferred Words.
INFO 2017-07-26 21:25:37,694 core.searchresults.score: Finished scoring search results.
ERROR 2017-07-26 21:25:37,694 cherrypy.error.34514216104.error: [26/Jul/2017:21:25:37] HTTP
Traceback (most recent call last):
  File "/usr/local/Watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/Watcher3/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/Watcher3/core/postprocessing.py", line 84, in POST
    response = self.complete(data)
  File "/usr/local/Watcher3/core/postprocessing.py", line 353, in complete
    if core.manage.searchresults(data['guid'], 'Finished', movie_info=data):
  File "/usr/local/Watcher3/core/library.py", line 841, in searchresults
    search_result = self.score.score([search_result], imported=True)[0]
IndexError: list index out of range
INFO 2017-07-26 21:25:37,695 cherrypy.error.34514216104.error: [26/Jul/2017:21:25:37] HTTP

name of the file was  This.Movie.1990.WEB-DL.720P.H264/ This.Movie.1990.WEB-DL.720P.H264.m4a
i created a post script in python to run manually and it failed the same way. 
i then renamed the folder and movie to just 'ThisMovie' and 'ThisMovie.m4a' and it worked.

if anyone wants the post script here you go.. (for python3)
```

#!/usr/local/bin/python

import json
import urllib
import urllib.request
import urllib.parse
import sys
import pprint
pp = pprint.PrettyPrinter(indent=4)

url = 'http://192.168.1.212:9090/postprocessing'
data = {'apikey': 'YOURAPIKEY', 'mode': 'complete', 'guid': sys.argv[2], 'path': sys.argv[1]}
print(data)

post_data = urllib.parse.urlencode(data).encode("utf-8")
webURL = urllib.request.urlopen(url,post_data)
data = webURL.read()
encoding = webURL.info().get_content_charset('utf-8')
r = json.loads(data.decode(encoding))
pp.pprint(r)

```

then just do 
./post.py MOVIEDIR GUID

*guid For NZB's the full download link to the file. For torrents or magnets use the torrent hash. Can be none as well, but search results will not be marked as Bad or Finished.

**Comment by nosmokingbandit** [comment]
The problem seems to be that removed the item based on its resolution, which shouldn't be happening.

Can you email me a link to that release so I can try it for myself and see what is going on?

`watchernzb@gmail.com`

**Comment by DraZtiK** [comment]
I just received this same error. I'm not using any post processing scripts from Watcher. I've sent you an email with the details to your email.

It seems after it found the release that the log stated it sent it to my downloader. nzbget, but nzbget never received the nzb. Afterwards I tried to tell Watcher to download again but instead i receive the 500 error.
