### ISSUE TITLE
500 error when trying to update / fetch an nzb

### ISSUE THREAD

**Issue by maxmarv** [nosmokingbandit/Watcher3#109]
Hello,

I manually installed Watcher on my synology box and first it seemed to be running fine but:

When I check for updates I get a 500 error and the log states:

INFO 2017-08-03 13:37:55,934 cherrypy.error.748198544.error: [03/Aug/2017:13:37:55] HTTP 
NameError: name 'commit_list' is not defined
    logging.debug('{} updates are available -- latest commit: {}.'.format(behind_count, commit_list[0]))
  File "/volume1/@appstore/Watcher3-master/core/version.py", line 366, in update_check
    response = self.version.manager.update_check()
  File "/volume1/@appstore/Watcher3-master/core/ajax.py", line 330, in update_check
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/Watcher3-master/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/volume1/@appstore/Watcher3-master/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/Watcher3-master/lib/cherrypy/lib/encoding.py", line 220, in __call__
    response.body = self.handler()
  File "/volume1/@appstore/Watcher3-master/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
ERROR 2017-08-03 13:37:55,932 cherrypy.error.748198544.error: [03/Aug/2017:13:37:55] HTTP 
INFO 2017-08-03 13:37:54,597 core.version.update_check: Checking git for a new Zip.

Yesterday I also noticed a 500 error when it tried to fetch an nzb:

INFO 2017-08-02 15:40:58,422 cherrypy.error.748198544.error: [02/Aug/2017:15:40:58] HTTP 
NameError: name 'nzb' is not defined
    logging.info('Sending NZB {} to NZBGet.'.format(nzb['title']))
  File "/volume1/@appstore/Watcher3-master/core/downloaders/nzbget.py", line 52, in add_nzb
    response = nzbget.Nzbget.add_nzb(data)
  File "/volume1/@appstore/Watcher3-master/core/snatcher.py", line 227, in snatch_nzb
    response = self.snatch_nzb(data)
  File "/volume1/@appstore/Watcher3-master/core/snatcher.py", line 174, in download
    return self.snatcher.download(data)
  File "/volume1/@appstore/Watcher3-master/core/ajax.py", line 242, in manual_download
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/Watcher3-master/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/volume1/@appstore/Watcher3-master/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/Watcher3-master/lib/cherrypy/lib/encoding.py", line 220, in __call__
    response.body = self.handler()
  File "/volume1/@appstore/Watcher3-master/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
ERROR 2017-08-02 15:40:58,420 cherrypy.error.748198544.error: [02/Aug/2017:15:40:58] HTTP 
INFO 2017-08-02 15:40:58,419 core.snatcher.snatch_nzb: Sending nzb to NzbGet.

Whats the issue? Any way I can help you debug this further?

**Comment by DraZtiK** [comment]
I had a similar issue. After the update no more issues.
to fix I shut Watcher down, did a git pull to update to the latest and then started Watcher again.

**Comment by maxmarv** [comment]
Thanks for your answer and trying to help!
I tried what you said even with removing the old directory to be completey fresh and now it won't even start up anymore:

Start services: Watcherash-4.3# Connected to database sqlite:////volume1/@appstore/Watcher3-master/watcher.sqlite
Subprocess error.
Traceback (most recent call last):
  File "/volume1/@appstore/Watcher3-master/core/version.py", line 115, in runner
    cwd=core.PROG_PATH
  File "/volume1/@appstore/python3/lib/python3.4/subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "/volume1/@appstore/python3/lib/python3.4/subprocess.py", line 1456, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
Config file not found. Creating new basic config /volume1/@appstore/Watcher3-master/config.cfg. Please review settings.
Clearing Mako cache.
Unable to clear Mako cache.
[Errno 2] No such file or directory: 'templates/cache'
Traceback (most recent call last):
  File "/volume1/@appstore/Watcher3-master/watcher.py", line 107, in <module>
    from core.app import App
  File "/volume1/@appstore/Watcher3-master/core/app.py", line 113
    return App.status_template.render(**self.defaults(), profiles=core.CONFIG['Quality']['Profiles'].keys(), movie_count=movie_count, hidden_count=hidden_count)
                                                       ^
SyntaxError: invalid syntax

**Comment by DraZtiK** [comment]
Not sure of your installation options but, If you have git installed you can use the Instructions from [here](https://github.com/nosmokingbandit/Watcher3/blob/master/README.md).

If you're just downloading the zip and extracting, are you setting the proper file/folder permissions? I believe your server is running a version of Linux and does it have Python3 installed and executing it properly `python3 watcher.py`?

I'm not sure of what your syntax error means.

**Comment by nosmokingbandit** [comment]
That error is the same as https://github.com/nosmokingbandit/Watcher3/issues/110, which is from an inconsistency in python versions. Pull or download the latest and you should be back in business.

**Comment by maxmarv** [comment]
Yeah that worked! Its starting up again. 
Now it complains about missing git which worked before although I can do a manual pull/clone in the directory so no biggie.

Subprocess error.
Traceback (most recent call last):
  File "/volume1/@appstore/Watcher3-master/core/version.py", line 112, in runner
    cwd=core.PROG_PATH
  File "/volume1/@appstore/python3/lib/python3.4/subprocess.py", line 858, in __                                         init__
    restore_signals, start_new_session)
  File "/volume1/@appstore/python3/lib/python3.4/subprocess.py", line 1456, in _                                         execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
Config file found, merging any new options.
Clearing Mako cache.

Thank you for the quick fix!

**Comment by nosmokingbandit** [comment]
How do you run git? It assumes git is in the PATH and can be run with `$
git`.

I think I meant to put an optional git path setting in at one point and
forgot all about it.

**Comment by maxmarv** [comment]
I'm pretty new at this so I ran it manually using the full path. Now i used "export git=xxx" to set the env variable and $git returns the main git binary. I hope thats correct? Still getting the error though.

**Comment by maxmarv** [comment]
Hej,

after your update and entering the git path everything is working great! Thank you :)

**Comment by nosmokingbandit** [comment]
Cool beans, I'll close this then.
