### ISSUE TITLE
attributerror: nonetype

### ISSUE THREAD

**Issue by phynias** [nosmokingbandit/Watcher3#111]
today i pulled the last and when i try and run watcher i get this.

# python watcher.py --daemon
Connected to database sqlite:////usr/local/Watcher3/watcher.sqlite
Config file found, merging any new options.
Clearing Mako cache.
Traceback (most recent call last):
  File "watcher.py", line 127, in <module>
    root = cherrypy.tree.mount(App(),
  File "/usr/local/Watcher3/core/app.py", line 37, in __init__
    scheduler.AutoUpdateCheck.update_check(install=False)
  File "/usr/local/Watcher3/core/scheduler.py", line 304, in update_check
    return ver.manager.update_check()
  File "/usr/local/Watcher3/core/version.py", line 61, in update_check
    core.scheduler_plugin.stop()
AttributeError: 'NoneType' object has no attribute 'stop'

**Comment by phynias** [comment]
ok this is weird. i did another pull and it grabbed more files. (now it says up to date) 
but i get more errors now.


python watcher.py --daemon
Connected to database sqlite:////usr/local/Watcher3/watcher.sqlite
Database update required. This may take some time.
Backing up database to /usr/local/Watcher3/db.
Executing database update 0
Executing database update 1
SQL Database Query: ['SELECT * FROM MOVIES  ORDER BY title ASC, sort_title ASC'].
Traceback (most recent call last):
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: sort_title

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Watcher3/core/sqldb.py", line 144, in execute
    result = self.engine.execute(*command)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/Watcher3/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/Watcher3/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: sort_title [SQL: 'SELECT * FROM MOVIES  ORDER BY title ASC, sort_title ASC']
SQL Databse Query: ['SELECT * FROM MOVIES  ORDER BY title ASC, sort_title ASC'].
Traceback (most recent call last):
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: sort_title

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Watcher3/core/sqldb.py", line 144, in execute
    result = self.engine.execute(*command)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/Watcher3/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/Watcher3/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: sort_title [SQL: 'SELECT * FROM MOVIES  ORDER BY title ASC, sort_title ASC']
Traceback (most recent call last):
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: sort_title

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "watcher.py", line 70, in <module>
    core.sql.update_database()
  File "/usr/local/Watcher3/core/sqldb.py", line 752, in update_database
    m()
  File "/usr/local/Watcher3/core/sqldb.py", line 773, in update_1
    for i in core.sql.get_user_movies():
  File "/usr/local/Watcher3/core/sqldb.py", line 302, in get_user_movies
    result = self.execute([command])
  File "/usr/local/Watcher3/core/sqldb.py", line 144, in execute
    result = self.engine.execute(*command)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/Watcher3/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/Watcher3/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Watcher3/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: sort_title [SQL: 'SELECT * FROM MOVIES  ORDER BY title ASC, sort_title ASC']

**Comment by nosmokingbandit** [comment]
I didn't look into the first error yet, but 5649c974b7f20186702b69a8866e6e520fac61f2 should fix the second post you made.

**Comment by phynias** [comment]
i think you can ignore the first one. think that was from a bad git pull.
