### ISSUE TITLE
Post Processing Script for NZBGet Reports 500 Error

### ISSUE THREAD

**Issue by dcplaya** [nosmokingbandit/Watcher3#126]
When I try and use the post processing script in NZBGet, the following error is reported

```
[INFO] Post-processing again MOVIE
[INFO] MOVIE returned from history back to download queue
[INFO] Queueing MOVIE for post-processing
[INFO] Pausing download before post-processing
[INFO] Cleaning up MOVIE
[INFO] Nothing to cleanup for MOVIE
[INFO] Unpausing download after post-processing
[INFO] Executing post-process-script watcher.py for MOVIE
[INFO] watcher: Sending MOVIE to Watcher as Complete.
[INFO] watcher: Traceback (most recent call last):
[INFO] watcher:   File "/config/scripts/watcher.py", line 72, in <module>
[INFO] watcher:     response = json.loads(urlopen(request, timeout=600).read().decode('utf-8'))
[INFO] watcher:   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
[INFO] watcher:     return opener.open(url, data, timeout)
[INFO] watcher:   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
[INFO] watcher:     response = meth(req, response)
[INFO] watcher:   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
[INFO] watcher:     'http', request, response, code, msg, hdrs)
[INFO] watcher:   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
[INFO] watcher:     return self._call_chain(*args)
[INFO] watcher:   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
[INFO] watcher:     result = func(*args)
[INFO] watcher:   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
[INFO] watcher:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
[INFO] watcher: urllib.error.HTTPError: HTTP Error 500: Internal Server Error
[ERROR] Post-process-script watcher.py for MOVIE failed (terminated with unknown status)
[INFO] Collection MOVIE added to history
```
The log reported from Watcher is

```
[19/Sep/2017:09:21:58] HTTP
Traceback (most recent call last):
  File "/app/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/watcher/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/app/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/watcher/core/postprocessing.py", line 80, in POST
    data.update(self.get_movie_info(data))
  File "/app/watcher/core/postprocessing.py", line 230, in get_movie_info
    mdata = self.metadata.from_file(data['movie_file'], imdbid=data.get('imdbid'))
  File "/app/watcher/core/library.py", line 435, in from_file
    titledata = self.parse_filename(filepath)
  File "/app/watcher/core/library.py", line 564, in parse_filename
    meta_data['edition'] = ' '.join(meta_data['edition'].sort())
TypeError: can only join an iterable
[19/Sep/2017:09:21:58] HTTP
Request Headers:
  Remote-Addr: 172.18.0.6
  ACCEPT-ENCODING: identity
  HOST: 172.18.0.8:9090
  USER-AGENT: Mozilla/5.0
  CONNECTION: close
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 322
172.18.0.6 - - [19/Sep/2017:09:21:58] "POST /postprocessing/ HTTP/1.1" 500 1905 "" "Mozilla/5.0"
```

When I have Watcher scan a directory instead of use the script, the same error pops up

```INFO 2017-09-19 09:28:42,142 core.library.from_file: Gathering metadata for /downloads/nzbget/completed/Movies/MOVIE.UNRATED.2017.1080p.BluRay.TrueHD.7.1.x264/462x.1.7.DHeurT.yaRulB.p0801.7102.DETARNU.hctawyaB.mkv.
INFO 2017-09-19 09:28:42,142 core.library.parse_filename: Parsing directory name for movie information: MOVIE.UNRATED.2017.1080p.BluRay.TrueHD.7.1.x264.
INFO 2017-09-19 09:28:42,153 core.library.parse_filename: Found {'year': 2017, 'resolution': '1080p', 'quality': 'BluRay', 'codec': 'x264', 'unrated': True, 'edition': ['UNRATED'], 'title': Movie', 'release_name': 'Movie.UNRATED.2017.1080p.BluRay.TrueHD.7.1.x264'} in filename.
WARNING 2017-09-19 09:28:42,153 CPTaskScheduler._task: Scheduled Task PostProcessing Scan Failed:
Traceback (most recent call last):
  File "/app/watcher/core/cp_plugins/taskscheduler.py", line 209, in _task
    self.task()
  File "/app/watcher/core/scheduler.py", line 107, in scan_directory
    pp.POST(**d)
  File "/app/watcher/core/postprocessing.py", line 80, in POST
    data.update(self.get_movie_info(data))
  File "/app/watcher/core/postprocessing.py", line 230, in get_movie_info
    mdata = self.metadata.from_file(data['movie_file'], imdbid=data.get('imdbid'))
  File "/app/watcher/core/library.py", line 435, in from_file
    titledata = self.parse_filename(filepath)
  File "/app/watcher/core/library.py", line 564, in parse_filename
    meta_data['edition'] = ' '.join(meta_data['edition'].sort())
TypeError: can only join an iterable
INFO 2017-09-19 09:28:42,165 CPTaskScheduler._task: == Finished Scheduled Task: PostProcessing Scan ==
```

I am running nzbget inside of a docker if that makes any difference.

**Comment by nosmokingbandit** [comment]
I wasn't able to reproduce, but I'm 90% sure e50ef1ebe827bd6680050c2933357ac1f3a733a5 will solve it. If it doesn't let me know and I'll run a few more movies through it to try to reproduce the error.

**Comment by dcplaya** [comment]
That seemed to have done it but I have not tried it with an "UNRATED" movie yet again. Ill close this for now since it seems to have fixed it.
