### ISSUE TITLE
Can't update. Problem to find git on Windows

### ISSUE THREAD

**Issue by nikogaug** [nosmokingbandit/Watcher3#15]
Hello,
I installed Watcher3 on windows 10 using GIT.
I can start it, configure it. But I have this error message :
"DEBUG 2017-04-10 14:16:02,237 core.notification.add: {'type': 'warning', 'title': 'Error Checking for Updates', 'body': ['[WinError 2] Le fichier spÃ©cifiÃ© est introuvable'], 'params': '{closeButton: true, timeOut: 0, extendedTimeOut: 0}', 'closeButton': 'true'}
DEBUG 2017-04-10 14:16:02,237 core.notification.add: Creating new notification:
INFO 2017-04-10 14:16:02,236 core.version.update_check: Checking git for a new version.
ERROR 2017-04-10 14:16:02,236 core.version.check_git_available: Could not execute git: ['[WinError 2] Le fichier spÃ©cifiÃ© est introuvable']
FileNotFoundError: [WinError 2] Le fichier spÃ©cifiÃ© est introuvable
    startupinfo)
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 990, in _execute_child
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 707, in __init__
    creationflags=CREATE_NO_WINDOW
  File "c:\watcher3\core\version.py", line 63, in runner
Traceback (most recent call last):
ERROR 2017-04-10 14:16:02,185 core.version.runner: Subprocess:"

I don't why it can't find GIT. Is it possible to specify where git is installed ?

**Comment by nikogaug** [comment]
Very sorry for disturbing. I installed the path of git. And now, it works !
Great thanks !
