### ISSUE TITLE
Scheduled Task Movie Search Failed

### ISSUE THREAD

**Issue by phynias** [nosmokingbandit/Watcher3#151]
noticed this in log. looks like the search gets about halfway through and then this.

```
WARNING 2017-11-18 14:05:05,885 CPTaskScheduler._task: Scheduled Task Movie Search Failed:
Traceback (most recent call last):
  File "/usr/local/Watcher3/core/cp_plugins/taskscheduler.py", line 254, in _task
    self.task()
  File "/usr/local/Watcher3/core/searcher.py", line 160, in search_all
    self.snatcher.grab_all()
  File "/usr/local/Watcher3/core/snatcher.py", line 66, in grab_all
    minscore = movie['finished_score'] + keepsearchingscore
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by nosmokingbandit** [comment]
4a1794296dcc9154c9d59374fdb75ec0b0c5f321

Should take care of this.
