### ISSUE TITLE
Improved Kodi Support

### ISSUE THREAD

**Issue by mrdeadlocked** [nosmokingbandit/Watcher3#154]
- Option to test connection settings to KODI for import + plugin
- Test notification on Kodi when connection successful.

I haven't been able to get the plugin to work for KODI. It loads and shows up in my plugins as 'finished'. Does 'finished' only work for items that are downloaded through Watcher? and not items that Watcher post processes from a directory?

**Comment by mrdeadlocked** [comment]
Trying to setup Watcher similiar to SickGear. Same settings work fine on SickGear but I get the following error in Watcher logs.

```
INFO 2017-11-20 12:46:40,193 core.downloaders.rtorrent.test_connection: Testing connection to rTorrent SGCI.
ERROR 2017-11-20 12:46:40,193 core.downloaders.rtorrent.test_connection: rTorrent connection test failed.
Traceback (most recent call last):
  File "/opt/Watcher3/core/downloaders/rtorrent.py", line 34, in test_connection
    client.system.time()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/opt/Watcher3/lib/rtorrent.py", line 165, in __request
    response = self.__transport.request(self.__host, self.__handler, request, verbose=self.__verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/Watcher3/lib/rtorrent.py", line 111, in single_request
    return self.parse_response(sock.makefile())
  File "/opt/Watcher3/lib/rtorrent.py", line 133, in parse_response
    p.close()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 447, in close
    parser.Parse(b"", True) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

![image](https://user-images.githubusercontent.com/461352/33019289-af74761e-cdc7-11e7-914f-5ee6570a6ce5.png)

![image](https://user-images.githubusercontent.com/461352/33019316-c98c9482-cdc7-11e7-959b-8bdffec14c88.png)

**Comment by nosmokingbandit** [comment]
Plugins are fired for all post-processed movies, including those from a scan. Your logs should indicate what is happening when the plugin is executed.

What version of rTorrent are you using? I have 0.9.6 in a virtual machine that is connecting fine.

**Comment by mrdeadlocked** [comment]
Same version 0.9.6. It works fine on other stuff.

**Comment by nosmokingbandit** [comment]
I'm not able to replicate this at all. The error means it is getting an empty response back from rTorrent, but it *is* getting a response. Are you able to send a torrent? To test the connection I just call system.time which sends back the time that rTorrent has, so if sending torrents works it might just be that method acting weird.

**Comment by mrdeadlocked** [comment]
No it says "× no element found: line 1, column 0" in the bottom right trying to send a torrent.

**Comment by nosmokingbandit** [comment]
I'm not able to replicate this. Does your rTorrent log indicate what is
happening during the request?

**Comment by mrdeadlocked** [comment]
I dont see anything popping up in the couple of rtorrent logs I could see. I have SickGear connecting across same settings and it sends items over without issue. Would you like anything else checked?

**Comment by nosmokingbandit** [comment]
I'm not sure what else *to* check. rTorrent's documentation is pretty sparse so it is hard to know exactly what is going on with it.

Do you mind sending me your rTorrent config? I'll use that on my copy and see if there is something I'm not aware of that could cause a problem.

`watchernzb@gmail.com`

**Comment by mrdeadlocked** [comment]
Sending now. Sorry been busy.

**Comment by nosmokingbandit** [comment]
Using your config I was unable to connect through either Watcher or Medusa. I had to change the port line to `scgi_port = 0.0.0.0:5040` and it worked fine for both applications.

What is odd is that my original config used `localhost:5000`, but that no longer works at all. Every time I use rTorrent it just feels janky to me and there is no documentation to speak of.

Anyway, try using `0.0.0.0` as the ip and see what happens.

**Comment by mrdeadlocked** [comment]
I'll give that a try. Thank you.
