### ISSUE TITLE
Type error when searching for torrent

### ISSUE THREAD

**Issue by throwaway1213** [nosmokingbandit/Watcher3#156]
`DEBUG 2017-11-20 21:41:18,481 core.sqldb.get_movie_details: Retrieving details for movie tt0451279.
DEBUG 2017-11-20 21:41:18,481 core.sqldb.execute: Executing SQL command: ['SELECT * FROM MOVIES WHERE imdbid="tt0451279"']
INFO 2017-11-20 21:41:18,482 core.searcher.search: Performing backlog search for Wonder Woman 2017.
INFO 2017-11-20 21:41:18,482 core.providers.newznab.search_all: Performing backlog search for all NewzNab indexers.
INFO 2017-11-20 21:41:18,482 core.providers.torrent.search: Performing backlog search on Torrentz2 for tt0451279.
INFO 2017-11-20 21:41:20,063 core.providers.torrent.parse: Parsing Torrentz2 results.
INFO 2017-11-20 21:41:20,072 core.providers.torrent.parse: Found 49 results from Torrentz2.
INFO 2017-11-20 21:41:20,072 core.providers.torrent.search: Performing backlog search on ThePirateBay for tt0451279.
INFO 2017-11-20 21:41:21,753 core.providers.torrent.parse: Parsing ThePirateBay results.
INFO 2017-11-20 21:41:21,755 core.providers.torrent.parse: Found 28 results from ThePirateBay.
INFO 2017-11-20 21:41:21,755 core.providers.torrent.search: Performing backlog search on YTS for tt0451279.
INFO 2017-11-20 21:41:25,156 core.providers.torrent.parse: Parsing 3 YTS results.
INFO 2017-11-20 21:41:25,157 core.providers.torrent.parse: Found 3 results from YTS.
DEBUG 2017-11-20 21:41:25,157 core.sqldb.get_search_results: Retrieving Search Results for tt0451279.
DEBUG 2017-11-20 21:41:25,157 core.sqldb.execute: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE imdbid="tt0451279" ORDER BY score DESC, size DESC, freeleech DESC']
INFO 2017-11-20 21:41:25,158 core.searcher.remove_inactive: Filtering releases based on enabled newznab indexers.
INFO 2017-11-20 21:41:25,158 core.searcher.get_source: Determining source media for [TransAngels] Chanel Santini, Lance Hart - Wonder Woman A XXX Trans Parody (13.11.2017) rq.mp4
INFO 2017-11-20 21:41:25,158 core.searcher.get_source: Source media determined as Unknown-SD
INFO 2017-11-20 21:41:25,158 core.searcher.get_source: Determining source media for Wonder.Woman.2017.BRRip.avi
INFO 2017-11-20 21:41:25,158 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,158 core.searcher.get_source: Determining source media for Wonder Woman (2017) [KiSS] 720pHD BluRay Mp4 Dual-Audio  AAC Multi-Subs
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Source media determined as BluRay-720P
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Determining source media for Wonder Woman (2017) 4K LAT - ZeiZ
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Source media determined as Unknown-4K
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Determining source media for Wonder.Woman.2017.BRRip.Isl.Texti.avi
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Determining source media for [TransAngels] Chanel Santini – Wonder Woman A XXX Trans Parody (2017-11-03) [1920x1080]
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Source media determined as Unknown-1080P
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Determining source media for Wonder.Woman.2017.720p.BluRay.FIX字幕侠
INFO 2017-11-20 21:41:25,159 core.searcher.get_source: Source media determined as BluRay-720P
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Determining source media for Wonder Woman '77 Meets the Bionic Woman v01 (2017) (digital) (Son of Ultron-Empire).cbr
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Source media determined as Unknown-SD
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Determining source media for Wonder.Woman.2017.720p.BluRay.x264-[YTS.AG].mp4
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Source media determined as BluRay-720P
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Determining source media for DC Week+ (05-10-2017)
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Source media determined as Unknown-SD
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Determining source media for Wonder Woman 2017  (2160p x265 10bit S77 Joy)
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Source media determined as Unknown-SD
INFO 2017-11-20 21:41:25,160 core.searcher.get_source: Determining source media for Wonder.Woman.2017.4K.UltraHD.BluRay.2160p.x264.TrueHD.7.1.Atmos-POOP
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Source media determined as BluRay-4K
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Determining source media for Wonder.Woman.2017.2160p.BluRay.SDR.8bit.UHD.4K.BDRip.x264.Master5.mkv
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Source media determined as BluRay-4K
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Determining source media for Wonder.Woman.2017_HDRip_r5.avi
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Source media determined as Unknown-SD
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Determining source media for Wonder Woman (2017) Hindi Dubbed Trailer ETTorrent
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Source media determined as Unknown-SD
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Determining source media for Wonder.Woman.2017.BDREMUX.2160p.4K.UltraHD.HEVC.HDR.mkv
INFO 2017-11-20 21:41:25,161 core.searcher.get_source: Source media determined as Unknown-4K
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Determining source media for [EX-TORRENTY.ORG] Wonder.Woman.2017.PLDUB.BRRip.720p.XviD.AC3-LTN
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Source media determined as BluRay-720P
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Determining source media for Wonder Woman 2017 BluRay x264 HD -TITAN
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Determining source media for Wonder Woman 2017 720p BrRip x264 - BATV
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Source media determined as BluRay-720P
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Determining source media for Wonder.Woman.2017.1080p.TWN.Blu-ray.AVC.TrueHD.7.1 - nLiBRA
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Source media determined as BluRay-1080P
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Determining source media for Wonder.Woman.2017.2160p.BluRay.x265.10bit.HDR.TrueHD.7.1.Atmos-EMERALD
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,162 core.searcher.get_source: Determining source media for Wonder.Woman.2017.720p.HDRiP.x264.AC3-MAJESTIC
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Source media determined as Unknown-720P
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Determining source media for Wonder.Woman.2017.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Determining source media for Wonder.Woman.2017.2160p.BluRay.x264.8bit.SDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Determining source media for Wonder.Woman.2017.BDREMUX.2160p.4K.UltraHD.HEVC.HDR.ExKinoRay.mkv
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Source media determined as Unknown-4K
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Determining source media for Wonder.Woman.2017.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,163 core.searcher.get_source: Determining source media for [ Torrent411.xyz ] Wonder.Woman.2017.FRENCH.BDRip.XviD-Shanks.avi
INFO 2017-11-20 21:41:25,164 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,164 core.searcher.get_source: Determining source media for Wonder.Woman.EXTRA.2017.BluRay.AC3.ENG.Subs.x264-WGZ
INFO 2017-11-20 21:41:25,164 core.searcher.get_source: Source media determined as BluRay-SD
INFO 2017-11-20 21:41:25,164 core.searcher.get_source: Determining source media for 2017
INFO 2017-11-20 21:41:25,164 cherrypy.error.2461974895136.error: [20/Nov/2017:21:41:25] HTTP 
Request Headers:
  HOST: localhost:9090
  REFERER: http://localhost:9090/library/status
  Content-Length: 16
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  X-REQUESTED-WITH: XMLHttpRequest
  DNT: 1
  Remote-Addr: 127.0.0.1
  COOKIE: advanced_toggle_checked=0; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; wanted_view=thumb; manage_view=thumb; session=9d21a02b1db85694e1351464bc6ccb2490741953
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  ACCEPT-ENCODING: gzip, deflate
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
  ACCEPT: */*
  CONNECTION: keep-alive
ERROR 2017-11-20 21:41:25,166 cherrypy.error.2461974895136.error: [20/Nov/2017:21:41:25] HTTP 
Traceback (most recent call last):
  File "G:\Torrent\Watcher3\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "G:\Torrent\Watcher3\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "G:\Torrent\Watcher3\lib\cherrypy\lib\jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "G:\Torrent\Watcher3\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "G:\Torrent\Watcher3\core\ajax.py", line 214, in search
    success = self.searcher.search(imdbid, movie['title'], movie['year'], movie['quality'])
  File "G:\Torrent\Watcher3\core\searcher.py", line 215, in search
    results[idx]['resolution'] = self.get_source(result)
  File "G:\Torrent\Watcher3\core\searcher.py", line 399, in get_source
    if any(i in title for i in ('4K', 'UHD', '2160P')):
  File "G:\Torrent\Watcher3\core\searcher.py", line 399, in <genexpr>
    if any(i in title for i in ('4K', 'UHD', '2160P')):
TypeError: argument of type 'int' is not iterable`

Happens when I search for the torrent via force backlog search.

**Comment by nosmokingbandit** [comment]
Somehow I missed this in my inbox until now....

It looks like the problem is one of the results has the simple title of `2017`, which the xmljson library parsed as an int rather than str.

3d3ac69b951c15b633aae80fd5386a9f2e4fea49 corrects this.
