### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ownz0rjoo** [nosmokingbandit/Watcher3#16]
Randomly started getting error 500, even after reboot etc. Not really sure how to get things back to normal. Any help is appreciated.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/ownz0rjoo/watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/ownz0rjoo/watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/ownz0rjoo/watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/ownz0rjoo/watcher3/templates/status.py", line 49, in default
    self.movie_list()
  File "/home/ownz0rjoo/watcher3/templates/status.py", line 97, in movie_list
    span(data['year'], cls='year')
  File "/home/ownz0rjoo/watcher3/lib/dominate/tags.py", line 63, in __init__
    super(html_tag, self).__init__(*args, **kwargs)
  File "/home/ownz0rjoo/watcher3/lib/dominate/dom_tag.py", line 93, in __init__
    self.add(*args)
  File "/home/ownz0rjoo/watcher3/lib/dominate/dom_tag.py", line 204, in add
    raise ValueError('%r not a tag or string.' % obj)
ValueError: None not a tag or string.
Powered by CherryPy unknown

**Comment by nosmokingbandit** [comment]
It looks like a movie in your library has no year associated with it. If you know what movies you added recently you can try removing them via an (api call)[https://github.com/nosmokingbandit/Watcher3/wiki/API] since the status page won't load.

If you find the imdb id# of the culprit let me know so I can figure out what went wrong so you can re-add it.

**Comment by ownz0rjoo** [comment]
thanks for the help this might sound dumb, but how can I determine my API key?

**Comment by ownz0rjoo** [comment]
Found my APIKey, now I'm trying to figure out a way to sort through this text dump.

**Comment by ownz0rjoo** [comment]
tt0859635

and 

tt1790810

All fixed.

**Comment by nosmokingbandit** [comment]
Cool beans, thanks.

They don't get a year from tmdb, which is the problem. I'll fix it soon.

**Comment by ridizy** [comment]
Had a movie that resulted in the above error.  I removed the movie and things were back to normal.  I then updated to https://github.com/nosmokingbandit/Watcher3/commit/07d69d097aededaeabad67663537a5345de6a7c6 and added the movie.  Error gone!
