### ISSUE TITLE
Error renaming "/home/plex/Downloads/watcher/_UNPACK_MOVIE" to "/home/plex/Downloads/watcher/MOVIE"

### ISSUE THREAD

**Issue by MechEng70** [nosmokingbandit/Watcher3#160]
SABdnzb reports that there is a error renaming the movie:

Error 1:
`Error renaming "/home/plex/Downloads/watcher/_UNPACK_MOVIE" to "/home/plex/Downloads/watcher/MOVIE"`
It is leaving the "_UNPACK_" portion of the title when moving it to the movie folder.

Error 2:
`Cannot change permissions of /home/plex/Downloads/watcher/_UNPACK_MOVIE`

Have checked all the permissions and they are set correctly.  The movie does get moved to the correct folder, it is the movie title that is not changed.

**Comment by nosmokingbandit** [comment]
Is this in your Sab log or Watcher log?

**Comment by MechEng70** [comment]
Sab....

**Comment by MechEng70** [comment]
Here is the log file from sab..

`2017-11-26 09:24:46,536::INFO::[newsunpack:267] Unrar finished on /home/plex/Downloads/incomplete/MOVIE
2017-11-26 09:24:46,540::INFO::[postproc:355] unpack_magic finished on MOVIE
2017-11-26 09:24:46,551::ERROR::[misc:1549] Cannot change permissions of /home/plex/Downloads/watcher/_UNPACK_MOVIE
2017-11-26 09:24:46,551::INFO::[misc:1550] Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/misc.py", line 1545, in set_chmod
    os.chmod(path, permissions)
OSError: [Errno 2] No such file or directory: '/home/plex/Downloads/watcher/_UNPACK_MOVIE'
2017-11-26 09:24:46,552::ERROR::[postproc:411] Error renaming "/home/plex/Downloads/watcher/_UNPACK_MOVIE" to "/home/plex/Downloads/watcher/MOVIE"
2017-11-26 09:24:46,553::INFO::[postproc:412] Traceback: 
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/postproc.py", line 409, in process_job
    newfiles = rename_and_collapse_folder(tmp_workdir_complete, workdir_complete, newfiles)
  File "/usr/share/sabnzbdplus/sabnzbd/postproc.py", line 913, in rename_and_collapse_folder
    renamer(oldpath, newpath)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/misc.py", line 1089, in renamer
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/plex/Downloads/watcher/_UNPACK_MOVIE'
2017-11-26 09:24:46,553::INFO::[postproc:528] Cleaning up MOVIE (keep_basic=False)
2017-11-26 09:24:46,869::INFO::[database:272] Added job MOVIE to history`

Does this help?

**Comment by nosmokingbandit** [comment]
Looks like that is a Sab problem. I believe this is taking place before Sab calls Watcher to finishing processing the download. I haven't used Sab in ages so I really can't point you in the right direction.
