### ISSUE TITLE
Issue with search (TypeError: 'str' object does not support item assignment)

### ISSUE THREAD

**Issue by cdonovan** [nosmokingbandit/Watcher3#161]
I'm getting an error when searching for movies.  This has been occurring for several days now.  I'm not sure if something changed in the format returned from Jackett or if it's something else.  When I manually run the queries noted in the logs, I see results being returned that would fit my quality profile.  If you need any further help debugging, please let me know.

INFO 2017-11-27 09:55:24,719 core.ajax.get_log_text: Dumping log file log.txt to text.
DEBUG 2017-11-27 09:55:05,260 core.sqldb.execute: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE imdbid="tt4649466" ORDER BY score DESC, size DESC, freeleech DESC']
DEBUG 2017-11-27 09:55:05,260 core.sqldb.get_search_results: Retrieving Search Results for tt4649466.
DEBUG 2017-11-27 09:55:05,259 core.sqldb.execute: Executing SQL command: ['SELECT * FROM MOVIES WHERE imdbid="tt4649466"']
DEBUG 2017-11-27 09:55:05,258 core.sqldb.get_movie_details: Retrieving details for movie tt4649466.
DEBUG 2017-11-27 09:55:05,254 core.sqldb.execute: Executing SQL command: ['UPDATE MOVIES SET backlog=? WHERE imdbid=?', ('1', 'tt4649466')]
DEBUG 2017-11-27 09:55:05,254 core.sqldb.update: Updating backlog to 1 for rows that match imdbid:tt4649466 in MOVIES.
DEBUG 2017-11-27 09:55:05,249 core.sqldb.execute: Executing SQL command: ['UPDATE MOVIES SET status=? WHERE imdbid=?', ('Waiting', 'tt4649466')]
DEBUG 2017-11-27 09:55:05,249 core.sqldb.update: Updating status to Waiting for rows that match imdbid:tt4649466 in MOVIES.
INFO 2017-11-27 09:55:05,248 core.library.movie_status: Setting MOVIES tt4649466 status to Waiting.
DEBUG 2017-11-27 09:55:05,246 core.sqldb.execute: Executing SQL command: ['SELECT DISTINCT status FROM SEARCHRESULTS WHERE imdbid="tt4649466"']
DEBUG 2017-11-27 09:55:05,246 core.sqldb.get_distinct: Getting distinct values for tt4649466 in SEARCHRESULTS
DEBUG 2017-11-27 09:55:05,245 core.sqldb.execute: Executing SQL command: ['SELECT * FROM MOVIES WHERE imdbid="tt4649466"']
DEBUG 2017-11-27 09:55:05,245 core.sqldb.get_movie_details: Retrieving details for movie tt4649466.
INFO 2017-11-27 09:55:05,244 core.library.movie_status: Determining appropriate status for movie tt4649466.
DEBUG 2017-11-27 09:55:05,242 core.sqldb.execute: Executing SQL command: ['DELETE FROM SEARCHRESULTS WHERE imdbid="tt4649466"']
DEBUG 2017-11-27 09:55:05,242 core.sqldb.purge_search_results: Purging search results for tt4649466
INFO 2017-11-27 09:55:05,242 core.searcher.store_results: Storing backlog search results -- purging existing results before writing to database.
INFO 2017-11-27 09:55:05,242 core.searcher.store_results: 0 results found for tt4649466. Storing results.
DEBUG 2017-11-27 09:55:05,241 core.sqldb.execute: Executing SQL command: ['SELECT * FROM MARKEDRESULTS WHERE imdbid="tt4649466"']
DEBUG 2017-11-27 09:55:05,241 core.sqldb.get_marked_results: Retrieving Marked Results for tt4649466.
INFO 2017-11-27 09:55:05,241 core.searchresults.score: Finished scoring search results.
INFO 2017-11-27 09:55:05,241 core.searchresults.score_preferred: Scoring Preferred Words.
INFO 2017-11-27 09:55:05,241 core.searchresults.fuzzy_title: Keeping 0 results.
INFO 2017-11-27 09:55:05,241 core.searchresults.fuzzy_title: Checking title match.
INFO 2017-11-27 09:55:05,240 core.searchresults.score_sources: Keeping 0 results.
INFO 2017-11-27 09:55:05,240 core.searchresults.score_sources: Filtering resolution and size requirements.
INFO 2017-11-27 09:55:05,240 core.searchresults.freeleech: Adding Freeleech points.
INFO 2017-11-27 09:55:05,240 core.searchresults.seed_check: Keeping 0 results.
INFO 2017-11-27 09:55:05,240 core.searchresults.seed_check: Checking torrent seeds.
INFO 2017-11-27 09:55:05,240 core.searchresults.retention_check: Keeping 0 results.
INFO 2017-11-27 09:55:05,240 core.searchresults.retention_check: Checking retention.
INFO 2017-11-27 09:55:05,240 core.searchresults.remove_ignored: Keeping 0 results.
INFO 2017-11-27 09:55:05,240 core.searchresults.remove_ignored: Filtering Ignored Words.
DEBUG 2017-11-27 09:55:05,240 core.searchresults.reset: Resetting release scores to 0.
DEBUG 2017-11-27 09:55:05,239 core.searchresults.score: Scoring based on quality profile Default
DEBUG 2017-11-27 09:55:05,238 core.sqldb.execute: Executing SQL command: ['SELECT * FROM MOVIES WHERE imdbid="tt4649466"']
DEBUG 2017-11-27 09:55:05,238 core.sqldb.get_movie_details: Retrieving details for movie tt4649466.
INFO 2017-11-27 09:55:05,238 core.searchresults.score: Scoring 0 search results.
INFO 2017-11-27 09:55:05,238 core.searcher.remove_inactive: Filtering releases based on enabled newznab indexers.
DEBUG 2017-11-27 09:55:05,235 core.sqldb.execute: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE imdbid="tt4649466" ORDER BY score DESC, size DESC, freeleech DESC']
DEBUG 2017-11-27 09:55:05,235 core.sqldb.get_search_results: Retrieving Search Results for tt4649466.
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,234 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,234 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,234 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,234 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,233 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,233 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,233 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,233 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,233 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,232 root.parse_newznab_xml: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "/opt/Watcher3/core/providers/base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING 2017-11-27 09:55:05,232 root.parse_newznab_xml: 
INFO 2017-11-27 09:55:02,614 root.search_newznab: SEARCHING: http://192.168.1.10:9117/api/v2.0/indexers/passthepopcorn/results/torznab/api?apikey=APIKEY&cat=2000&imdbid=tt4649466&t=movie
INFO 2017-11-27 09:55:02,614 core.providers.torrent.search_all: http://192.168.1.10:9117/api/v2.0/indexers/passthepopcorn/results/torznab/ supports imdbid search.
DEBUG 2017-11-27 09:55:02,613 core.sqldb.execute: Executing SQL command: ['SELECT "caps" FROM CAPS WHERE url="http://192.168.1.10:9117/api/v2.0/indexers/passthepopcorn/results/torznab/"']
DEBUG 2017-11-27 09:55:02,613 core.sqldb.torznab_caps: Retreiving caps for http://192.168.1.10:9117/api/v2.0/indexers/passthepopcorn/results/torznab/
INFO 2017-11-27 09:55:02,613 core.providers.torrent.search_all: Searching TorzNab indexer http://192.168.1.10:9117/api/v2.0/indexers/passthepopcorn/results/torznab/

**Comment by cdonovan** [comment]
This issue appears fixed with the recent refactor/redesign.  Closing this out.
