### ISSUE TITLE
Traceback when postprocessing 

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/Watcher3#166]
Log is backwards, if it wasn't clear...

```
DEBUG 2017-12-04 10:13:46,811 core.sqldb.row_exists: Checking if name="PostProcessing Scan" exists in database table TASKS
AttributeError: 'NoneType' object has no attribute 'rfind'
    i = p.rfind(sep) + 1
  File "/usr/lib/python3.4/posixpath.py", line 103, in split
    dirname = os.path.split(filepath)[0].split(os.sep)[-1]
  File "/opt/Watcher3/core/library.py", line 553, in parse_filename
    titledata = self.parse_filename(filepath)
  File "/opt/Watcher3/core/library.py", line 450, in from_file
    mdata = self.metadata.from_file(data['movie_file'], imdbid=data.get('imdbid'))
  File "/opt/Watcher3/core/postprocessing.py", line 230, in get_movie_info
    data.update(self.get_movie_info(data))
  File "/opt/Watcher3/core/postprocessing.py", line 80, in default
    pp.default(**d)
  File "/opt/Watcher3/core/scheduler.py", line 118, in scan_directory
    self.task()
  File "/opt/Watcher3/core/cp_plugins/taskscheduler.py", line 254, in _task
Traceback (most recent call last):
WARNING 2017-12-04 10:13:46,810 CPTaskScheduler._task: Scheduled Task PostProcessing Scan Failed:
INFO 2017-12-04 10:13:46,810 core.library.from_file: Gathering metadata for None.
INFO 2017-12-04 10:13:46,809 core.postprocessing.get_movie_info: Unable to find local data for release. Using only data found from file.
INFO 2017-12-04 10:13:46,809 core.postprocessing.get_movie_info: Unable to find local release info by release name.
DEBUG 2017-12-04 10:13:46,798 core.sqldb.execute: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE title="Big.Brother.US.S19E28.WEB.x264-TBS" ORDER BY score DESC, size DESC']
D
```

**Comment by nosmokingbandit** [comment]
Can you get me the log starting with the beginning of the post-processing
request? I think it was unable to find a file to process but I'm not 100%
with that snippet.

**Comment by barbequesauce** [comment]
There's a file there - it's not a movie though.

```
INFO 2017-12-05 13:13:51,567 core.postprocessing.default: #################################
INFO 2017-12-05 13:13:51,567 core.postprocessing.default: Post-processing request received.
INFO 2017-12-05 13:13:51,567 core.postprocessing.default: #################################
DEBUG 2017-12-05 13:13:51,567 core.postprocessing.default: {'guid': 'POSTPROCESSING4269672E42726F74', 'path': '/mnt/skytopcliff/completed/Big.Brother.US.S19E28.WEB.x264-TBS', 'apikey': 'a8472302cae387e4c13bdabb295e5a1a', 'mode': 'complete', 'downloadid': ''}
INFO 2017-12-05 13:13:51,568 core.postprocessing.get_movie_file: Finding movie file.
INFO 2017-12-05 13:13:51,569 core.postprocessing.get_movie_file: Post-processing file None.
INFO 2017-12-05 13:13:51,569 core.postprocessing.default: Gathering release information.
INFO 2017-12-05 13:13:51,569 core.postprocessing.get_movie_info: Searching local database for guid.
DEBUG 2017-12-05 13:13:51,570 core.sqldb.get_single_search_result: Retrieving search result details for POSTPROCESSING4269672E42726F74.
DEBUG 2017-12-05 13:13:51,570 core.sqldb.execute: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE guid="POSTPROCESSING4269672E42726F74" ORDER BY score DESC, size DESC']
INFO 2017-12-05 13:13:51,579 core.postprocessing.get_movie_info: Unable to find local release info by guid.
INFO 2017-12-05 13:13:51,580 core.postprocessing.get_movie_info: Guid not found.
INFO 2017-12-05 13:13:51,580 core.postprocessing.get_movie_info: Searching local database for release name Big.Brother.US.S19E28.WEB.x264-TBS
DEBUG 2017-12-05 13:13:51,580 core.sqldb.get_single_search_result: Retrieving search result details for Big.Brother.US.S19E28.WEB.x264-TBS.
DEBUG 2017-12-05 13:13:51,581 core.sqldb.execute: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE title="Big.Brother.US.S19E28.WEB.x264-TBS" ORDER BY score DESC, size DESC']
INFO 2017-12-05 13:13:51,589 core.postprocessing.get_movie_info: Unable to find local release info by release name.
INFO 2017-12-05 13:13:51,590 core.postprocessing.get_movie_info: Unable to find local data for release. Using only data found from file.
INFO 2017-12-05 13:13:51,590 core.library.from_file: Gathering metadata for None.
WARNING 2017-12-05 13:13:51,590 CPTaskScheduler._task: Scheduled Task PostProcessing Scan Failed:
Traceback (most recent call last):
  File "/opt/Watcher3/core/cp_plugins/taskscheduler.py", line 254, in _task
    self.task()
  File "/opt/Watcher3/core/scheduler.py", line 118, in scan_directory
    pp.default(**d)
  File "/opt/Watcher3/core/postprocessing.py", line 80, in default
    data.update(self.get_movie_info(data))
  File "/opt/Watcher3/core/postprocessing.py", line 230, in get_movie_info
    mdata = self.metadata.from_file(data['movie_file'], imdbid=data.get('imdbid'))
  File "/opt/Watcher3/core/library.py", line 450, in from_file
    titledata = self.parse_filename(filepath)
  File "/opt/Watcher3/core/library.py", line 553, in parse_filename
    dirname = os.path.split(filepath)[0].split(os.sep)[-1]
  File "/usr/lib/python3.4/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by barbequesauce** [comment]
Can't reproduce at this point, so closing the issue.
