### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Joecastra** [nosmokingbandit/Watcher3#17]
Have just tried to install on a fresh raspberry pi installation
and recieved the following when trying to start
Traceback (most recent call last):
  File "watcher.py", line 13, in <module>
    from core import api, config, postprocessing, scheduler, sqldb
  File "/opt/watcher/core/api.py", line 6, in <module>
    from core import ajax, sqldb, poster
  File "/opt/watcher/core/ajax.py", line 9, in <module>
    from core import config, library, plugins, poster, searchresults, searcher, snatcher, sqldb, version
  File "/opt/watcher/core/library.py", line 3, in <module>
    from hachoir.parser import createParser
  File "/opt/watcher/lib/hachoir/parser/__init__.py", line 1, in <module>
    from hachoir.parser.parser import ValidateError, HachoirParser, Parser  # noqa
  File "/opt/watcher/lib/hachoir/parser/parser.py", line 142
    print("- %s: %s" % (tags["id"], tags["description"]), file=out)
                                                              ^
SyntaxError: invalid syntax

i am running the latest xbian release

**Comment by nosmokingbandit** [comment]
Looks like you are launching it with Python2. 

You should be able to install Python3 with `sudo apt-get install python3`, then launch with `python3 watcher.py`
