### ISSUE TITLE
Errors With Newznab Indexers

### ISSUE THREAD

**Issue by LeeThompson** [nosmokingbandit/Watcher3#170]
This is a fairly recent problem, I'm not sure exactly which update pull started it but anyway:

Here's a log excerpt, I've redacted a private spotweb based indexer.

```
INFO [2017-12-11 22:56:19,299] root.search_newznab.36: SEARCHING: https://api.dognzb.cr/api?apikey=APIKEY&t=movie&imdbid=1736555
INFO [2017-12-11 22:56:19,299] core.providers.newznab.search_all.36: Searching NewzNab indexer https://api.dognzb.cr
KeyError: 'item'
    items = channel['item']
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 118, in parse_newznab_xml
Traceback (most recent call last):
ERROR [2017-12-11 22:56:19,298] root.parse_newznab_xml.120: Unexpected XML format from NewzNab indexer.
INFO [2017-12-11 22:56:18,502] root.search_newznab.36: SEARCHING: https://6box.me/api?apikey=APIKEY&t=movie&imdbid=1736555
INFO [2017-12-11 22:56:18,502] core.providers.newznab.search_all.36: Searching NewzNab indexer https://6box.me
KeyError: 'rss'
    channel = gdata.data(fromstring(feed))['rss']['channel']
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 116, in parse_newznab_xml
Traceback (most recent call last):
ERROR [2017-12-11 22:56:18,501] root.parse_newznab_xml.120: Unexpected XML format from NewzNab indexer.
INFO [2017-12-11 22:56:18,417] root.search_newznab.36: SEARCHING: http://|REDACTED_SPOTWEB|/api?apikey=APIKEY&t=movie&imdbid=1736555
INFO [2017-12-11 22:56:18,416] core.providers.newznab.search_all.36: Searching NewzNab indexer http://|REDACTED_SPOTWEB|/
KeyError: 'item'
    items = channel['item']
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 118, in parse_newznab_xml
Traceback (most recent call last):
ERROR [2017-12-11 22:56:18,416] root.parse_newznab_xml.120: Unexpected XML format from NewzNab indexer.
INFO [2017-12-11 22:56:17,709] root.search_newznab.36: SEARCHING: https://nzbfinder.ws/api?apikey=APIKEY&t=movie&imdbid=1736555
INFO [2017-12-11 22:56:17,709] core.providers.newznab.search_all.36: Searching NewzNab indexer https://nzbfinder.ws/
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,709] root.parse_newznab_xml.157: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,709] root.parse_newznab_xml.157: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,709] root.parse_newznab_xml.157: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,708] root.parse_newznab_xml.157: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,708] root.parse_newznab_xml.157: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,708] root.parse_newznab_xml.157: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,708] root.parse_newznab_xml.157: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,708] root.parse_newznab_xml.157: 
TypeError: 'str' object does not support item assignment
    item['attr'] = {}
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 125, in parse_newznab_xml
Traceback (most recent call last):
WARNING [2017-12-11 22:56:17,707] root.parse_newznab_xml.157: 
INFO [2017-12-11 22:56:15,430] root.search_newznab.36: SEARCHING: https://api.nzbgeek.info/api?apikey=APIKEY&t=movie&imdbid=1736555
INFO [2017-12-11 22:56:15,430] core.providers.newznab.search_all.36: Searching NewzNab indexer https://api.nzbgeek.info/
INFO [2017-12-11 22:56:13,860] root.search_newznab.36: SEARCHING: http://www.usenet-crawler.com/api?apikey=APIKEY&t=movie&imdbid=1736555
INFO [2017-12-11 22:56:13,860] core.providers.newznab.search_all.36: Searching NewzNab indexer http://www.usenet-crawler.com/
KeyError: 'item'
    items = channel['item']
  File "C:\Program Files (x86)\Watcher\Watcher3\core\providers\base.py", line 118, in parse_newznab_xml
Traceback (most recent call last):
ERROR [2017-12-11 22:56:13,840] root.parse_newznab_xml.120: Unexpected XML format from NewzNab indexer.

```

**Comment by nosmokingbandit** [comment]
I just tested with Usenet Crawler and it worked as expected. Are you using NZBHydra or something similar?

**Comment by LeeThompson** [comment]
Nope.

**Comment by nosmokingbandit** [comment]
With another imdb id it works fine, ie `https://www.usenet-crawler.com/api?apikey=NOPE&t=movie&imdbid=2140479`

Does this occur with all movies or just tt0101807?

I'm not able to get it to throw as many errors are you are getting no matter what I attempt to search.

Try entering  `http://www.usenet-crawler.com/api?apikey=APIKEY&t=movie&imdbid=0101807` in your browser (with your api key of course) and see if the xml looks like this:

```
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<atom:link href="https://www.usenet-crawler.com/api?apikey=APIKEY&t=movie&imdbid=0101807" rel="self" type="application/rss+xml"/>
<title>usenet-crawler</title>
<description>usenet-crawler Feed</description>
<link>https://www.usenet-crawler.com/</link>
<language>en-gb</language>
<webMaster>info@usenet-crawler.com (usenet-crawler)</webMaster>
<category/>
<image>
<url>
https://www.usenet-crawler.com/views/images/logo.png
</url>
<title>usenet-crawler</title>
<link>https://www.usenet-crawler.com/</link>
<description>Visit usenet-crawler - A quick usenet indexer</description>
</image>
<newznab:response offset="0" total="0"/>
</channel>
</rss>
```
