### ISSUE TITLE
After download and import, "Keep Searching" fails with TypeError (macOS, Python 3.6.3)

### ISSUE THREAD

**Issue by Alrescha-git** [nosmokingbandit/Watcher3#180]
After a successful snatch, download, and postprocessing, subsequent Movie Searches fail with a TypeError until the "Keep Searching" time expires.

WARNING [2017-12-20 20:37:10,775] CPTaskScheduler._task.256: Scheduled Task Movie Search Failed:
Traceback (most recent call last):
  File "/Users/test/Downloads/Watcher3/core/cp_plugins/taskscheduler.py", line 254, in _task
    self.task()
  File "/Users/test/Downloads/Watcher3/core/searcher.py", line 160, in search_all
    self.snatcher.grab_all()
  File "/Users/test/Downloads/Watcher3/core/snatcher.py", line 66, in grab_all
    minscore = movie.get('finished_score', 0) + keepsearchingscore
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by nosmokingbandit** [comment]
Does this still happen after d07898490bcf216dfd6bdd95d73d00c45c8e847f?

**Comment by Alrescha-git** [comment]
No.  No more failures after the update.
