### ISSUE TITLE
Traceback: Invalid or corrupt torrent file.

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/Watcher3#188]
Hi - I received this a dozen or so times over the weekend each time the search thread went looking. I wound up deleting the movie as it was a mistaken addition by someone else... but I thought you might want to know anyway.

```
INFO [2018-01-07 20:15:20,769] core.snatcher.grab_all.54: MOVIE status is Found. Running automatic snatcher.
INFO [2018-01-07 20:15:20,769] core.snatcher.best_release.88: Selecting best release for MOVIE
DEBUG [2018-01-07 20:15:20,770] core.sqldb.get_search_results.415: Retrieving Search Results for tt1230168.
DEBUG [2018-01-07 20:15:20,770] core.sqldb.execute.146: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE imdbid="tt1230168" ORDER BY score DESC, size DESC, freeleech DESC']
INFO [2018-01-07 20:15:20,800] core.snatcher.best_release.138: MOVIE 2017 1080p WEB-DL DD5 1 H264-FGT is best available result for MOVIE
INFO [2018-01-07 20:15:20,801] core.snatcher.download.160: Sending MOVIE2017 1080p WEB-DL DD5 1 H264-FGT to download client.
INFO [2018-01-07 20:15:20,801] core.snatcher.snatch_torrent.287: Sending torrent to Transmission.
INFO [2018-01-07 20:15:20,802] core.downloaders.transmission.add_torrent.52: Sending torrent MOVIE 2017 1080p WEB-DL DD5 1 H264-FGT to Transmission.
ERROR [2018-01-07 20:15:22,716] core.downloaders.transmission.add_torrent.92: Unable to send torrent to TransmissionRPC.
Traceback (most recent call last):
  File "/opt/Watcher3/core/downloaders/transmission.py", line 85, in add_torrent
    download = client.add_torrent(url, paused=paused, bandwidthPriority=bandwidthPriority, download_dir=download_dir, timeout=30)
  File "/opt/Watcher3/lib/transmissionrpc/client.py", line 418, in add_torrent
    return list(self._request('torrent-add', args, timeout=timeout).values())[0]
  File "/opt/Watcher3/lib/transmissionrpc/client.py", line 263, in _request
    raise TransmissionError('Query failed with result \"%s\".' % (data['result']))
transmissionrpc.error.TransmissionError: Query failed with result "invalid or corrupt torrent file".
```

Edited by @nosmokingbandit to remove media names

**Comment by nosmokingbandit** [comment]
I was able to find that release on a site I use and it submitted to Transmission without incident. Whatever indexer supplied the torrent might have just had something corrupt in the file.

Unfortunately, I'm not sure there is much I can do to catch this in the future. I could simply set that release as bad, but if Watcher isn't able to communicate with the download client it may blacklist releases that aren't bad.

**Comment by barbequesauce** [comment]
I get that - i was more pointing out the existence of a condition causing a traceback than the cause of the condition, if that makes any sense...
