### ISSUE TITLE
Nested tracebacks with RARBG

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/Watcher3#189]
This started coming up earlier today - it's probably transient by the looks of it, but maybe worth a look:

```
INFO [2018-01-08 13:06:38,991] core.providers.torrent.get_rss.291: Fetching latest RSS from Rarbg.
INFO [2018-01-08 13:06:38,996] core.providers.torrent._get_token.325: Getting RarBG access token.
ERROR [2018-01-08 13:07:09,755] core.providers.torrent.get_rss.316: Rarbg RSS fetch failed.
Traceback (most recent call last):
  File "/opt/Watcher3/lib/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/Watcher3/lib/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 617, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Watcher3/lib/requests/adapters.py", line 436, in send
    timeout=timeout
  File "/opt/Watcher3/lib/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/Watcher3/lib/requests/packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/Watcher3/lib/requests/packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/opt/Watcher3/lib/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/Watcher3/lib/requests/packages/urllib3/connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/Watcher3/lib/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
lib.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.torrentapi.org', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Watcher3/core/providers/torrent.py", line 305, in get_rss
    response = Url.open(url).text
  File "/opt/Watcher3/core/helpers.py", line 84, in open
    r = requests.get(url, **kwargs)
  File "/opt/Watcher3/lib/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/Watcher3/lib/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/Watcher3/lib/requests/sessions.py", line 497, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/Watcher3/lib/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/Watcher3/lib/requests/adapters.py", line 512, in send
    raise ReadTimeout(e, request=request)
lib.requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.torrentapi.org', port=443): Read timed out. (read timeout=30)

```

**Comment by nosmokingbandit** [comment]
Yeah, that error looks like Rarbg didn't respond within 30 seconds. I wouldn't worry about it unless it happens regularly. Their api is pretty amazing, but this kind of thing happens.
