### ISSUE TITLE
Error during movie search scheduled task.

### ISSUE THREAD

**Issue by blakeaa827** [nosmokingbandit/Watcher3#220]
I don't believe this is breaking anything, but I'm seeing an error popup in bottom right corner.  Here's the log.  Let me know if you need anything else to troubleshoot.

INFO [2018-02-22 19:31:01,178] core.searcher.get_source.396: Determining source media for OrderedDict()
WARNING [2018-02-22 19:31:01,178] CPTaskScheduler._task.256: Scheduled Task Movie Search Failed:
Traceback (most recent call last):
  File "/opt/Watcher3/core/cp_plugins/taskscheduler.py", line 254, in _task
    self.task()
  File "/opt/Watcher3/core/searcher.py", line 151, in search_all
    self.search(imdbid, title, year, quality)
  File "/opt/Watcher3/core/searcher.py", line 215, in search
    results[idx]['resolution'] = self.get_source(result)
  File "/opt/Watcher3/core/searcher.py", line 399, in get_source
    if any(i in title.upper() for i in ('4K', 'UHD', '2160P')):
  File "/opt/Watcher3/core/searcher.py", line 399, in <genexpr>
    if any(i in title.upper() for i in ('4K', 'UHD', '2160P')):
AttributeError: 'collections.OrderedDict' object has no attribute 'upper'
INFO [2018-02-22 19:31:01,184] CPTaskScheduler._task.265: == Finished Scheduled Task: Movie Search ==

**Comment by nosmokingbandit** [comment]
What python version are you using? You can find out by running `python -V`.


Can you send the logs to `watchernzb@gmail.com?` I'm going to assume you
are using torrents and this is probably something to due with parsing a
feed.
