### ISSUE TITLE
Error since commit fd77a42

### ISSUE THREAD

**Issue by j0hnsen** [nosmokingbandit/Watcher3#24]
Hey,
since fd77a42 I got a wired error...

Traceback (most recent call last):
  File "watcher.py", line 17, in <module>
    import core
  File "/root/watcher/core/__init__.py", line 31, in <module>
    NO_VERIFY = ssl._create_unverified_context()
AttributeError: 'module' object has no attribute '_create_unverified_context'

Could you please fix this asap!

**Comment by nosmokingbandit** [comment]
What version of python?

**Comment by j0hnsen** [comment]
Python 3.4.2

**Comment by nosmokingbandit** [comment]
Git automatically closed this when I pushed the update, but let me know if this fixes it for you. It should be compatible with python 3.x.

Do you know how to update without going through the UI?
