### ISSUE TITLE
Not able to connect to Deluge WebUI

### ISSUE THREAD

**Issue by MarioCaires** [nosmokingbandit/Watcher3#243]
** Commit:
** OS: unRaid 6.5.0
** Python Version [python -V]: Python 3.5.2
** What happened: When connecting Deluge WebUI, it gives error below 
** Logs:
If logs contain information you do not wish to share with the world you may email them to `watchernzb@gmail.com`. Include the issue number in the subject line of the message.
```
INFO [2018-04-20 13:54:38,547] core.ajax.get_log_text.515: Dumping log file log.txt to text.
lib.requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.11', port=8112): Max retries exceeded with url: /json (Caused by NewConnectionError('<lib.requests.packages.urllib3.connection.HTTPConnection object at 0x14e26b8f0748>: Failed to establish a new connection: [Errno 113] No route to host',))
raise ConnectionError(e, request=request)
File "/watcher/lib/requests/adapters.py", line 500, in send
r = adapter.send(request, **kwargs)
File "/watcher/lib/requests/sessions.py", line 618, in send
resp = self.send(prep, **send_kwargs)
File "/watcher/lib/requests/sessions.py", line 497, in request
return session.request(method=method, url=url, **kwargs)
File "/watcher/lib/requests/api.py", line 58, in request
return request('post', url, data=data, json=json, **kwargs)
File "/watcher/lib/requests/api.py", line 112, in post
r = requests.post(url, **kwargs)
File "/watcher/core/helpers.py", line 86, in open
response = Url.open(url, post_data=post_data, headers=headers)
File "/watcher/core/downloaders/DelugeWeb.py", line 234, in _login
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

lib.requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.11', port=8112): Max retries exceeded with url: /json (Caused by NewConnectionError('<lib.requests.packages.urllib3.connection.HTTPConnection object at 0x14e26b8f0748>: Failed to establish a new connection: [Errno 113] No route to host',))
raise MaxRetryError(_pool, url, error or ResponseError(cause))
File "/watcher/lib/requests/packages/urllib3/util/retry.py", line 376, in increment
_stacktrace=sys.exc_info()[2])
File "/watcher/lib/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
timeout=timeout
File "/watcher/lib/requests/adapters.py", line 436, in send
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

lib.requests.packages.urllib3.exceptions.NewConnectionError: <lib.requests.packages.urllib3.connection.HTTPConnection object at 0x14e26b8f0748>: Failed to establish a new connection: [Errno 113] No route to host
self, "Failed to establish a new connection: %s" % e)
File "/watcher/lib/requests/packages/urllib3/connection.py", line 150, in _new_conn
conn = self._new_conn()
File "/watcher/lib/requests/packages/urllib3/connection.py", line 166, in connect
self.connect()
File "/usr/lib/python3.5/http/client.py", line 877, in send
self.send(msg)
File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
self._send_output(message_body)
File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
self.endheaders(body)
File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
self._send_request(method, url, body, headers)
File "/usr/lib/python3.5/http/client.py", line 1106, in request
conn.request(method, url, **httplib_request_kw)
File "/watcher/lib/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
chunked=chunked)
File "/watcher/lib/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

OSError: [Errno 113] No route to host
sock.connect(sa)
File "/watcher/lib/requests/packages/urllib3/util/connection.py", line 73, in create_connection
raise err
File "/watcher/lib/requests/packages/urllib3/util/connection.py", line 83, in create_connection
(self.host, self.port), self.timeout, **extra_kw)
File "/watcher/lib/requests/packages/urllib3/connection.py", line 141, in _new_conn
Traceback (most recent call last):
ERROR [2018-04-20 13:54:33,191] core.downloaders.DelugeWeb._login.249: DelugeWeb test_connection
INFO [2018-04-20 13:54:30,116] core.downloaders.DelugeWeb._login.223: Logging in to Deluge Web UI.
INFO [2018-04-20 13:54:30,115] core.downloaders.DelugeWeb.test_connection.26: Testing connection to Deluge Web UI.
```

**Comment by MarioCaires** [comment]
Fixed!
Just had to assign a different IP to the Watcher container. Somehow doesn't work if it have the same IP as the host!
