### ISSUE TITLE
Server error viewing /settings/system

### ISSUE THREAD

**Issue by DeftNerd** [nosmokingbandit/Watcher3#264]
** Commit: 1440799
** Operating System: Ubuntu 18.04 LTS
** Python Version: Python 2.7.15rc1
** What happened: Viewing /settings/system results in an error
** Logs:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/Watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Watcher3/core/app.py", line 198, in settings
    return App.system_template.render(config=core.CONFIG['System'], tasks=json.dumps(tasks), system=system, server_time=[dt, t], **self.defaults())
  File "/opt/Watcher3/lib/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/opt/Watcher3/lib/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/opt/Watcher3/lib/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/opt/Watcher3/lib/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/opt/Watcher3/templates/cache/templates/settings/system.html.py", line 60, in render_body
    __M_writer(str(config['FileManagement']['missingfileaction']))
KeyError: 'missingfileaction'
```

```
INFO [2018-07-25 08:02:09,045] core.ajax.get_log_text.512: Dumping log file log.txt to text.
USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.103 Safari/537.36
UPGRADE-INSECURE-REQUESTS: 1
REFERER: http://127.0.0.1:9090/settings/postprocessing
DNT: 1
COOKIE: lang=en-US; hide_finished_movies=False; movie_sort_direction=desc; movie_layout=posters; session=2ec987b535a777b8c28693ac53163b983ee8aa5b; movie_sort_key=release_date
ACCEPT-LANGUAGE: en-US
ACCEPT-ENCODING: gzip, deflate, br
ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
CONNECTION: keep-alive
HOST: 127.0.0.1:9090
Remote-Addr: 127.0.0.1
Request Headers:
INFO [2018-07-25 08:01:08,659] cherrypy.error.139626307590072.error.219: [25/Jul/2018:08:01:08] HTTP 
KeyError: 'missingfileaction'
__M_writer(str(config['FileManagement']['missingfileaction']))
File "/opt/Watcher3/templates/cache/templates/settings/system.html.py", line 60, in render_body
callable_(context, *args, **kwargs)
File "/opt/Watcher3/lib/mako/runtime.py", line 899, in _exec_template
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "/opt/Watcher3/lib/mako/runtime.py", line 873, in _render_context
**_kwargs_for_callable(callable_, data))
File "/opt/Watcher3/lib/mako/runtime.py", line 838, in _render
return runtime._render(self, self.callable_, args, data)
File "/opt/Watcher3/lib/mako/template.py", line 462, in render
return App.system_template.render(config=core.CONFIG['System'], tasks=json.dumps(tasks), system=system, server_time=[dt, t], **self.defaults())
File "/opt/Watcher3/core/app.py", line 198, in settings
return self.callable(*self.args, **self.kwargs)
File "/opt/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
self.body = self.oldhandler(*args, **kwargs)
File "/opt/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
response.body = self.handler()
File "/opt/Watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
ERROR [2018-07-25 08:01:08,658] cherrypy.error.139626307590072.error.219: [25/Jul/2018:08:01:08] HTTP 
USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.103 Safari/537.36
UPGRADE-INSECURE-REQUESTS: 1
REFERER: http://127.0.0.1:9090/settings/postprocessing
DNT: 1
COOKIE: lang=en-US; hide_finished_movies=False; movie_sort_direction=desc; movie_layout=posters; session=2ec987b535a777b8c28693ac53163b983ee8aa5b; movie_sort_key=release_date
ACCEPT-LANGUAGE: en-US
ACCEPT-ENCODING: gzip, deflate, br
ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
CONNECTION: keep-alive
HOST: 127.0.0.1:9090
Remote-Addr: 127.0.0.1
Request Headers:
INFO [2018-07-25 07:59:36,996] cherrypy.error.139626307590072.error.219: [25/Jul/2018:07:59:36] HTTP 
KeyError: 'missingfileaction'
__M_writer(str(config['FileManagement']['missingfileaction']))
File "/opt/Watcher3/templates/cache/templates/settings/system.html.py", line 60, in render_body
callable_(context, *args, **kwargs)
File "/opt/Watcher3/lib/mako/runtime.py", line 899, in _exec_template
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "/opt/Watcher3/lib/mako/runtime.py", line 873, in _render_context
**_kwargs_for_callable(callable_, data))
File "/opt/Watcher3/lib/mako/runtime.py", line 838, in _render
return runtime._render(self, self.callable_, args, data)
File "/opt/Watcher3/lib/mako/template.py", line 462, in render
return App.system_template.render(config=core.CONFIG['System'], tasks=json.dumps(tasks), system=system, server_time=[dt, t], **self.defaults())
File "/opt/Watcher3/core/app.py", line 198, in settings
return self.callable(*self.args, **self.kwargs)
File "/opt/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
self.body = self.oldhandler(*args, **kwargs)
File "/opt/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
response.body = self.handler()
File "/opt/Watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
ERROR [2018-07-25 07:59:36,996] cherrypy.error.139626307590072.error.219: [25/Jul/2018:07:59:36] HTTP 
USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.103 Safari/537.36
UPGRADE-INSECURE-REQUESTS: 1
REFERER: http://127.0.0.1:9090/settings/server
DNT: 1
COOKIE: lang=en-US; hide_finished_movies=False; movie_sort_direction=desc; movie_layout=posters; session=2ec987b535a777b8c28693ac53163b983ee8aa5b; movie_sort_key=release_date
ACCEPT-LANGUAGE: en-US
ACCEPT-ENCODING: gzip, deflate, br
ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
CONNECTION: keep-alive
HOST: 127.0.0.1:9090
Remote-Addr: 127.0.0.1
Request Headers:
```

**Comment by UnR34L** [comment]
Same issue, Python 3.6.5

**Comment by whispy** [comment]
Same issue.

**Comment by UnR34L** [comment]
Fixed for me. 👍
