### ISSUE TITLE
500 Internal Server Error on search

### ISSUE THREAD

**Issue by DavidAdams** [nosmokingbandit/Watcher3#270]
** Commit: 1908318847b207394424e75c7091813e7350366b
** Operating System: Synology Linux
** Python Version [python -V]: 3.5
** What happened: Attempted forced search, received red pop up box with "500 Internal Server Error"
** Logs:
```
INFO [2018-08-10 21:17:12,855] cherrypy.error.140713571041120.error.219: [10/Aug/2018:21:17:12] HTTP 
UnboundLocalError: local variable 'movie_details' referenced before assignment
quality_profile = movie_details['quality']
File "/path/to/Watcher3/core/searchresults.py", line 54, in score
scored_results = searchresults.score(results, imdbid=imdbid)
File "/path/to/Watcher3/core/searcher.py", line 152, in search
success = searcher.search(imdbid, movie['title'], movie['year'], movie['quality'])
File "/path/to/Watcher3/core/ajax.py", line 227, in search
return self.callable(*self.args, **self.kwargs)
File "/path/to/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
File "/path/to/Watcher3/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
self.body = self.oldhandler(*args, **kwargs)
File "/path/to/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
response.body = self.handler()
File "/path/to/Watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
ERROR [2018-08-10 21:17:12,307] cherrypy.error.140713571041120.error.219: [10/Aug/2018:21:17:12] HTTP 
INFO [2018-08-10 21:17:12,306] core.searchresults.score.38: Scoring 6 releases.
```

**Comment by Dammi87** [comment]
Had the same problem, apparently some restructure of the code was made in the latest commit.
I reverted to the previous one
`
git checkout 4789bdaaf57fda1282083927e5bdf984a2541a95`

**Comment by nosmokingbandit** [comment]
Should be back to normal in 4d9764881baddda454f6ffa774ebacad6c85b6ef

Sorry about that, stupid oversight when I try to write quickly.
