### ISSUE TITLE
DelugeRPC does not handle invalid credentials gracefully

### ISSUE THREAD

**Issue by fourbytes** [nosmokingbandit/Watcher3#271]
When the given deluge username/password are incorrect, watcher will appear to connect successfully when pressing test, however when saving, it will throw an *Unable to retrieve download path.* error.

Test console:
```python
>>> client.call('core.get_config')
b'Auth level too low: 0 < 5'
>>> client.call('core.get_config')[b'download_location'].decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: byte indices must be integers or slices, not bytes
```

Actual Watcher3 log:
```
INFO [2018-08-17 02:10:13,472] core.ajax.get_log_text.512: Dumping log file log.txt to text.
TypeError: byte indices must be integers or slices, not bytes
def_download_path = client.call('core.get_config')[b'download_location'].decode('utf-8')
File "/app/watcher/core/downloaders/DelugeRPC.py", line 71, in add_torrent
Traceback (most recent call last):
ERROR [2018-08-17 02:08:54,665] core.downloaders.DelugeRPC.add_torrent.73: Unable to get download path.
INFO [2018-08-17 02:08:54,658] core.downloaders.DelugeRPC.add_torrent.51: Sending torrent >torrent<.
```

**Comment by nosmokingbandit** [comment]
Looks like the deluge user doesn't have proper permission. 

https://dev.deluge-torrent.org/wiki/UserGuide/Authentication

You'll want to edit Deluge's config to give your user at leave level 5 authentication. It might need 10, but I don't think so. I haven't used Deluge in a long time.

**Comment by fourbytes** [comment]
Yea, I actually had the username incorrect, the main issue was more that the connection test should never really succeed, as it's quite misleading.
