### ISSUE TITLE
Post-processing seems to fail if the release isn't in db.

### ISSUE THREAD

**Issue by fourbytes** [nosmokingbandit/Watcher3#273]
```
INFO [2018-08-19 00:49:37,911] CPTaskScheduler._task.273: == Finished Task: PostProcessing Scan ==
KeyError: 'title'
titles = [movie_details['title']]
File "/app/watcher/core/searchresults.py", line 93, in score
search_result = searchresults.score([search_result], imported=True)[0]
File "/app/watcher/core/library.py", line 944, in searchresults
if Manage.searchresults(data['guid'], 'Finished', movie_info=data):
File "/app/watcher/core/postprocessing.py", line 482, in complete
response = self.complete(data)
File "/app/watcher/core/postprocessing.py", line 196, in default
pp.default(**d)
File "/app/watcher/core/scheduler.py", line 130, in scan_directory
self.task()
File "/app/watcher/lib/cherrypyscheduler.py", line 264, in _task
Traceback (most recent call last):
WARNING [2018-08-19 00:49:37,717] CPTaskScheduler._task.266: Scheduled Task PostProcessing Scan Failed:
INFO [2018-08-19 00:49:37,717] core.searchresults.score_sources.415: Keeping 1 releases.
INFO [2018-08-19 00:49:37,717] core.searchresults.score_sources.378: Filtering resolution and size requirements.
INFO [2018-08-19 00:49:37,717] core.searchresults.score.38: Scoring 1 releases.
INFO [2018-08-19 00:49:37,717] core.searchresults.generate_simulacrum.447: Creating "fake" search result for imported movie Movie Name
INFO [2018-08-19 00:49:37,716] core.library.searchresults.932: Guid postprocessing416e742d4d616e2e not found in SEARCHRESULTS, attempting to create entry.
INFO [2018-08-19 00:49:37,713] core.library.searchresults.919: Marking guid postprocessing416e742d4d616e2e as Finished.
INFO [2018-08-19 00:49:37,713] core.postprocessing.complete.478: Marking guid as Finished.
INFO [2018-08-19 00:49:37,713] core.postprocessing.default.194: Post-processing as Complete.
INFO [2018-08-19 00:49:36,724] core.movieinfo._search_tmdbid.157: Searching TMDB https://api.themoviedb.org/3/movie/102899?language=en-US&append_to_response=alternative_titles,external_ids,release_dates
INFO [2018-08-19 00:49:36,723] core.movieinfo._search_tmdbid.153: Searching TheMovieDB for TMDB ID: 102899.
INFO [2018-08-19 00:49:35,744] core.movieinfo._search_title.97: Searching TMDB https://api.themoviedb.org/3/search/movie?page=1&include_adult=false&query=movie name&year=2015
INFO [2018-08-19 00:49:35,744] core.movieinfo._search_title.86: Searching TheMovieDB for title: Movie Name 2015.
INFO [2018-08-19 00:49:35,744] core.movieinfo.search.59: Searching TheMovieDB for Movie Name 2015
INFO [2018-08-19 00:49:35,718] core.library.parse_media.450: Parsing codec data from file /downloads/deluge/completed/watcher/Movie.Name.2015.1080p.BluRay.x264-SPARKS[rarbg]/Movie.Name.2015.1080p.BluRay.x264-SPARKS.mkv.
INFO [2018-08-19 00:49:35,718] core.library.parse_filename.512: Found {'year': 2015, 'resolution': '1080p', 'quality': 'BluRay', 'codec': 'x264', 'title': 'Movie Name', 'group': 'SPARKS[rarbg]', 'release_name': 'Movie.Name.2015.1080p.BluRay.x264-SPARKS[rarbg]'} in filename.
INFO [2018-08-19 00:49:35,718] core.library.parse_filename.504: Parsing directory name for movie information: Movie.Name.2015.1080p.BluRay.x264-SPARKS[rarbg].
INFO [2018-08-19 00:49:35,718] core.library.from_file.380: Gathering metadata for /downloads/deluge/completed/watcher/Movie.Name.2015.1080p.BluRay.x264-SPARKS[rarbg]/Movie.Name.2015.1080p.BluRay.x264-SPARKS.mkv.
INFO [2018-08-19 00:49:35,718] core.postprocessing.get_movie_info.331: Unable to find local data for release. Using only data found from file.
INFO [2018-08-19 00:49:35,718] core.postprocessing.get_movie_info.313: Unable to find local release info by release name.
INFO [2018-08-19 00:49:35,715] core.postprocessing.get_movie_info.308: Searching local database for release name Movie.Name.2015.1080p.BluRay.x264-SPARKS[rarbg]
INFO [2018-08-19 00:49:35,715] core.postprocessing.get_movie_info.292: Guid not found.
INFO [2018-08-19 00:49:35,715] core.postprocessing.get_movie_info.289: Unable to find local release info by guid.
INFO [2018-08-19 00:49:35,712] core.postprocessing.get_movie_info.284: Searching local database for guid.
INFO [2018-08-19 00:49:35,712] core.postprocessing.default.186: Gathering release information.
INFO [2018-08-19 00:49:35,712] core.postprocessing.get_movie_file.262: Largest file in directory /downloads/deluge/completed/watcher/Move.Name.2015.1080p.BluRay.x264-SPARKS[rarbg] is /Movie.Name.2015.1080p.BluRay.x264-SPARKS.mkv, processing this file.
INFO [2018-08-19 00:49:35,712] core.postprocessing.get_movie_file.236: Finding movie file.
INFO [2018-08-19 00:49:35,712] core.postprocessing.default.158: #################################
INFO [2018-08-19 00:49:35,712] core.postprocessing.default.157: Post-processing request received.
INFO [2018-08-19 00:49:35,712] core.postprocessing.default.156: #################################
```

Could also be good if post-processing didn't stop if one file causes an exception.

**Comment by UnR34L** [comment]
It's happening for me as well.

**Comment by nosmokingbandit** [comment]
I believe this is the same as #253. If not let me know and I'll reopen, but until then we'll discus it there.
