### ISSUE TITLE
Push Bullet Finished Notify issue

### ISSUE THREAD

**Issue by xGBHxPegasus** [nosmokingbandit/Watcher3#279]
** Commit: 0217e75158b563bdefc8e01c3be7620008cf3977
** Operating System: Windows 10
** Python Version [python -V]: 3.7 (x64)
** What happened: When a movie finishes no PushBullet notification is sent, the below is in the log.txt within Watcher. When a media is snatched notifications work perfectly.
** Logs:
If logs contain information you do not wish to share with the world you may email them to `watchernzb@gmail.com`. Include the issue number in the subject line of the message.
```
PASTE LOGS HERE
INFO [2018-11-07 17:33:17,719] CPTaskScheduler._task.273: == Finished Task: PostProcessing Scan ==
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'Traceback (most recent call last):'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'  File "C:\\Watcher\\Watcher3\\plugins\\finished\\Pushbullet Notify.py", line 15, in <module>'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'    conf = json.loads(conf_json)'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'  File "C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python37\\lib\\json\\__init__.py", line 348, in loads'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'    return _default_decoder.decode(s)'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'  File "C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python37\\lib\\json\\decoder.py", line 337, in decode'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'    obj, end = self.raw_decode(s, idx=_w(s, 0).end())'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'  File "C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python37\\lib\\json\\decoder.py", line 355, in raw_decode'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'    raise JSONDecodeError("Expecting value", s, err.value) from None'
INFO [2018-11-07 17:33:17,953] core.plugins.execute.263: Pushbullet Notify.py - b'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)'
WARNING [2018-11-07 17:33:17,953] core.plugins.execute.267: Pushbullet Notify.py - Execution failed. Exit code 1.

**Comment by nosmokingbandit** [comment]
Looks like the config for the Finished plugin is nonexistent or corrupted.
