### ISSUE TITLE
Jackett snatching failure: Unable to get torrent hash from indexer

### ISSUE THREAD

**Issue by grooveborg** [nosmokingbandit/Watcher3#285]
** Commit: 0217e75
** Operating System: Ubuntu 16.04.4 LTS (Docker)
** Python Version [python -V]: Python 3.5.2

** What happened: Automatic snatching fails from TorzNab indexer (Jackett). Manual snatching fails with error notification "Unable to get torrent hash from indexer."

** Logs:
```
INFO [2018-11-15 19:33:55,949] core.ajax.get_log_text.512: Dumping log file log.txt to text.
lib.requests.exceptions.InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:F1B200A509D8DA43CAC1BB8C0ED2F851BDB80C45&dn=A.Boy.and.His.Dog.1975.1080p.BluRay.X264-AMIABLE+[PublicHD]&tr=udp:%2F%2Ffr33domtracker.h33t.com:3310%2Fannounce&tr=http:%2F%2Ffr33dom.h33t.com:3310%2Fannounce&tr=udp:%2F%2Ftracker.publichd.eu%2Fannounce&tr=udp:%2F%2Ftracker.openbittorrent.com:80&tr=udp:%2F%2Ftracker.istole.it:80&tr=udp:%2F%2Ftracker.ccc.de:80&tr=udp:%2F%2Ftracker.yify-torrents.com%2Fannounce&tr=udp:%2F%2Ftracker.openbittorrent.ca:80&tr=udp:%2F%2F12.rarbg.me:80%2Fannounce&tr=udp:%2F%2Fexodus.desync.com:6969&tr=udp:%2F%2Ftracker.publicbt.com:80&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce'
raise InvalidSchema("No connection adapters were found for '%s'" % url)
File "/watcher/lib/requests/sessions.py", line 695, in get_adapter
adapter = self.get_adapter(url=request.url)
File "/watcher/lib/requests/sessions.py", line 612, in send
**adapter_kwargs
File "/watcher/lib/requests/sessions.py", line 194, in resolve_redirects
history = [resp for resp in gen] if allow_redirects else []
File "/watcher/lib/requests/sessions.py", line 639, in <listcomp>
history = [resp for resp in gen] if allow_redirects else []
File "/watcher/lib/requests/sessions.py", line 639, in send
resp = self.send(prep, **send_kwargs)
File "/watcher/lib/requests/sessions.py", line 497, in request
return session.request(method=method, url=url, **kwargs)
File "/watcher/lib/requests/api.py", line 58, in request
return request('get', url, params=params, **kwargs)
File "/watcher/lib/requests/api.py", line 72, in get
r = requests.get(url, **kwargs)
File "/watcher/core/helpers.py", line 90, in open
raw = torrent if file_bytes else Url.open(torrent, stream=True).content
File "/watcher/core/helpers.py", line 159, in get_hash
Traceback (most recent call last):
ERROR [2018-11-15 19:33:43,075] root.get_hash.164: Unable to get torrent hash
INFO [2018-11-15 19:33:42,714] core.snatcher.download.162: Sending A.Boy.and.His.Dog.1975.1080p.BluRay.X264-AMIABLE [PublicHD] to download client.
```

**Comment by swmiller6** [comment]
I am having the same issue.
