### ISSUE TITLE
SQL Error On Search

### ISSUE THREAD

**Issue by LeeThompson** [nosmokingbandit/Watcher3#298]
I'm getting a database error on search with some movies, the log shows this:

```
Traceback (most recent call last):
  File "/opt/watcher3/app/lib/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/opt/watcher3/app/lib/sqlalchemy/engine/default.py", line 459, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 6 - probably unsupported type.
```

**Comment by LeeThompson** [comment]
Still getting this from time to time, seems kinda random.  If you want full debug logs I can e-mail them to you (not comfortable posting them here.)

It seems to occur if too many search results come back (or some of the indexers are sending back something SQLite doesn't like.)
