### ISSUE TITLE
Post Processing Script Failure

### ISSUE THREAD

**Issue by bartley69** [nosmokingbandit/Watcher3#299]
** Current Version Hash: 0217e75158b563bdefc8e01c3be7620008cf3977
** Operating System: QNAP NAS
** Python Version [python -V]: Python 2.7.15 (default, Sep 08 2018, 20:33:38)
** What happened: I cannot get the post processing script to function. I have correctly edited the watcher.py file, created the category in sabnzbd as required, however when it tries to process a download i am given a urllib2.URLError. Any idea what is causing this? This is the log from SABnzbd.
```
Traceback (most recent call last):
File "/share/Download/nzbToMedia/watcher.py", line 65, in <module>
response = urlopen(req, timeout=60, context=ctx).read().decode('utf-8')
File "/opt/lib/python2.7/urllib2.py", line 154, in urlopen
File "/opt/lib/python2.7/urllib2.py", line 429, in open
File "/opt/lib/python2.7/urllib2.py", line 447, in _open
File "/opt/lib/python2.7/urllib2.py", line 407, in _call_chain
File "/opt/lib/python2.7/urllib2.py", line 1228, in http_open
File "/opt/lib/python2.7/urllib2.py", line 1198, in do_open
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```
Thanks.

**Comment by bartley69** [comment]
Solved.

It appears it didn't like me using my actual IP of my nas for the locations of my programs. Changing them to localhost solved my issue!

Thank you for a great program.

[img]https://i.gyazo.com/ca90b7d4d45fea4409f178672e5046d6.png[/img]
