### ISSUE TITLE
After nzbget runs the watcher script it will return a KeyError: 'movie_file'

### ISSUE THREAD

**Issue by PotatoQuality** [nosmokingbandit/Watcher3#30]
After  nzbget starts watcher.py it will fail with a 500 http error

````
ERROR	Mon Apr 24 2017 21:04:34	Post-process-script Watcher.py3 for xxxxxxxxxxxxxx failed (terminated with unknown status)
INFO	Mon Apr 24 2017 21:04:34	Watcher: urllib.error.HTTPError: HTTP Error 500: Internal Server Error
INFO	Mon Apr 24 2017 21:04:34	Watcher: raise HTTPError(req.full_url, code, msg, hdrs, fp)
INFO	Mon Apr 24 2017 21:04:34	Watcher: File "C:\Python3\lib\urllib\request.py", line 650, in http_error_default
INFO	Mon Apr 24 2017 21:04:34	Watcher: result = func(*args)
INFO	Mon Apr 24 2017 21:04:34	Watcher: File "C:\Python3\lib\urllib\request.py", line 504, in _call_chain
INFO	Mon Apr 24 2017 21:04:34	Watcher: return self._call_chain(*args)
INFO	Mon Apr 24 2017 21:04:34	Watcher: File "C:\Python3\lib\urllib\request.py", line 570, in error
INFO	Mon Apr 24 2017 21:04:34	Watcher: 'http', request, response, code, msg, hdrs)
INFO	Mon Apr 24 2017 21:04:34	Watcher: File "C:\Python3\lib\urllib\request.py", line 642, in http_response
INFO	Mon Apr 24 2017 21:04:34	Watcher: response = meth(req, response)
INFO	Mon Apr 24 2017 21:04:34	Watcher: File "C:\Python3\lib\urllib\request.py", line 532, in open
INFO	Mon Apr 24 2017 21:04:34	Watcher: return opener.open(url, data, timeout)
INFO	Mon Apr 24 2017 21:04:34	Watcher: File "C:\Python3\lib\urllib\request.py", line 223, in urlopen
INFO	Mon Apr 24 2017 21:04:34	Watcher: response = json.loads(urlopen(request, timeout=600).read().decode('utf-8'))
INFO	Mon Apr 24 2017 21:04:34	Watcher: File "D:\cache nzbget\scripts\Watcher.py3", line 72, in <module>
INFO	Mon Apr 24 2017 21:04:34	Watcher: Traceback (most recent call last):
INFO	Mon Apr 24 2017 21:04:34	Watcher: Sending xxxxxxxxxxxxxxx to Watcher as Complete.
INFO	Mon Apr 24 2017 21:04:32	Executing post-process-script Watcher.py3 for XXXXXXXXXXXXX

````

Wacher log:

````
INFO 2017-04-24 21:04:34,016 cherrypy.error.90438064.error: [24/Apr/2017:21:04:34] HTTP 
KeyError: 'movie_file'
    data.update(self.metadata.get_metadata(data['movie_file']))
  File "C:\watcher\core\postprocessing.py", line 223, in get_movie_info
    data.update(self.get_movie_info(data))
  File "C:\watcher\core\postprocessing.py", line 82, in POST
    return self.callable(*self.args, **self.kwargs)
  File "C:\watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    response.body = self.handler()
  File "C:\watcher\lib\cherrypy\_cprequest.py", line 670, in respond
Traceback (most recent call last):

````

**Comment by j0hnsen** [comment]
Same issue is here #27 

Sometimes I ask myself if the dev ever tests his work?

**Comment by PotatoQuality** [comment]
Well, its a opensource software. I like watcher its light and runs great. But beceause its writing by a human, sometimes you will make a little stupid error. He will fix it soon. Don't worry about it

**Comment by nosmokingbandit** [comment]
Heh I just opened a new issue to separate it from #27.

This problem makes no sense. The line directly above this method call assigns that value. I'm working on it.

**Comment by PotatoQuality** [comment]
@nosmokingbandit if you need more logging ore something i can do. Tell me :)

**Comment by nosmokingbandit** [comment]
Github automatically closed this when I pushed the fix, but let me know if you still have trouble with it.

**Comment by j0hnsen** [comment]
Sorry to reopen it again but I still got this error :(
If you need logfiles just say it I could send them :)

**Comment by PotatoQuality** [comment]
Did you update to the last version and did you update your postprocess file?

It works for me btw

**Comment by j0hnsen** [comment]
Yep each 2-5 download fails with this 500er error... It's wired even after reboot and copy of the nzbget PP script.

**Comment by PotatoQuality** [comment]
Wait, what is your error in de log file of watcher? A 500 error in nzbget doesn't mean you have still the same error. Its a general error that something was going wrong on the site of watcher. But the problem in watcher van be different

**Comment by j0hnsen** [comment]
Some log output

INFO 2017-04-25 18:02:11,367 core.movieinfo._search_title: Searching TMDB https://api.themoviedb.org/3/search/movie?page=1&include_adult=false&query=the+wedding+date+german&year=2005
WARNING 2017-04-25 18:02:11,764 core.library.get_metadata: Unable to get data from TMDB for 
INFO 2017-04-25 18:02:11,774 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-04-25 18:02:11,775 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-04-25 18:02:11,775 core.postprocessing.complete: Imdbid not supplied or found, unable to update Movie status.
INFO 2017-04-25 18:02:11,775 cherrypy.error.139865164675560.error: [25/Apr/2017:18:02:11] HTTP 
ERROR 2017-04-25 18:02:11,775 cherrypy.error.139865164675560.error: [25/Apr/2017:18:02:11] HTTP

**Comment by PotatoQuality** [comment]
That Isn't the whole output. Nosmokingbandit need te trackback log

**Comment by j0hnsen** [comment]
Yep will send him but can't paste public ;-)

**Comment by nosmokingbandit** [comment]
Got your logs, thanks.

Commit https://github.com/nosmokingbandit/Watcher3/commit/1e020f65bf6bf3d7de4288dd2def0787d1e0a5bb correct this in my tests. I can only try to break it so many ways, so let me know if you still have trouble with it (ideally just open a new issue).
