### ISSUE TITLE
nzbToWatcher3 CherryPy Error

### ISSUE THREAD

**Issue by rafaello104** [nosmokingbandit/Watcher3#312]
Steps:
- I manually click a download option on my move (this example: Rampage)
- nzb gets sent to my nzbget client (on same machine)
- nzb download fails, nzbget runs nzbToWatcher3
- nzbToWatcher3 reaches Watcher3 successfully
- A couple warnings happen, the script terminates with unknown status
- The log states: `missing api key` but my api key is present (as you can see in the request)
- The movie in Watcher3 still has status `snatched`
** The movie should get status `failed` and try again**

Question:
Is this a bug or am I doing something wrong?

Provide all information requested below. Issues without adequate information will be closed without response.

** Commit: `0217e75158b563bdefc8e01c3be7620008cf3977`
** Operating System: `Windows 10 Pro Build 1909`
** Python Version [python -V]: `3.7.7`
** What happened: `See steps above`
** Logs:
```
INFO [2020-03-24 19:36:59,919] core.postprocessing.default.156: #################################
INFO [2020-03-24 19:36:59,919] core.postprocessing.default.157: Post-processing request received.
INFO [2020-03-24 19:36:59,919] core.postprocessing.default.158: #################################
WARNING [2020-03-24 19:36:59,919] core.postprocessing.default.163: Missing key apikey
INFO [2020-03-24 19:37:01,939] core.postprocessing.default.156: #################################
INFO [2020-03-24 19:37:01,939] core.postprocessing.default.157: Post-processing request received.
INFO [2020-03-24 19:37:01,939] core.postprocessing.default.158: #################################
DEBUG [2020-03-24 19:37:01,939] core.postprocessing.default.176: {'apikey': 'MY_CORRECT_API_KEY', 'path': 'E:\\NZBs\\Incomplete\\Rampage.2018.TrueHD.Atmos.AC3.MULTISUBS.1080p.BluRay.x264.1.HQ-TUSAHD.#19956', 'guid': '', 'mode': 'failed'}
INFO [2020-03-24 19:37:01,939] core.postprocessing.get_movie_file.236: Finding movie file.
WARNING [2020-03-24 19:37:01,939] core.postprocessing.get_movie_file.264: Unable to determine largest file. Postprocessing may fail at a later point.
INFO [2020-03-24 19:37:01,940] core.postprocessing.default.186: Gathering release information.
INFO [2020-03-24 19:37:01,940] core.postprocessing.get_movie_info.292: Guid not found.
INFO [2020-03-24 19:37:01,940] core.postprocessing.get_movie_info.308: Searching local database for release name Rampage.2018.TrueHD.Atmos.AC3.MULTISUBS.1080p.BluRay.x264.1.HQ-TUSAHD.#19956
DEBUG [2020-03-24 19:37:01,940] core.sqldb.get_single_search_result.601: Retrieving search result details for Rampage.2018.TrueHD.Atmos.AC3.MULTISUBS.1080p.BluRay.x264.1.HQ-TUSAHD.#19956.
DEBUG [2020-03-24 19:37:01,940] core.sqldb.execute.156: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE title="Rampage.2018.TrueHD.Atmos.AC3.MULTISUBS.1080p.BluRay.x264.1.HQ-TUSAHD.#19956" ORDER BY score DESC, size DESC']
INFO [2020-03-24 19:37:01,946] core.postprocessing.get_movie_info.313: Unable to find local release info by release name.
INFO [2020-03-24 19:37:01,946] core.postprocessing.get_movie_info.331: Unable to find local data for release. Using only data found from file.
WARNING [2020-03-24 19:37:01,947] core.postprocessing.default.191: Post-processing as Failed.
INFO [2020-03-24 19:37:01,947] core.postprocessing.failed.368: Marking guid as Bad.
ERROR [2020-03-24 19:37:01,947] cherrypy.error.2092576679432.error.219: [24/Mar/2020:19:37:01] HTTP 
Traceback (most recent call last):
  File "C:\Users\Admin\Watcher3\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Users\Admin\Watcher3\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Admin\Watcher3\lib\cherrypy\lib\jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "C:\Users\Admin\Watcher3\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Admin\Watcher3\core\postprocessing.py", line 192, in default
    response = self.failed(data)
  File "C:\Users\Admin\Watcher3\core\postprocessing.py", line 402, in failed
    if data['imdbid']:
KeyError: 'imdbid'
INFO [2020-03-24 19:37:01,971] cherrypy.error.2092576679432.error.219: [24/Mar/2020:19:37:01] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: localhost:9090
  USER-AGENT: python-requests/2.21.0
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT: */*
  CONNECTION: keep-alive
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 168
DEBUG [2020-03-24 19:38:45,003] core.sqldb.get_user_movies.327: Retrieving list of user's movies.
DEBUG [2020-03-24 19:38:45,004] core.sqldb.execute.156: Executing SQL command: ['SELECT * FROM MOVIES  ORDER BY sort_title ASC LIMIT 50 OFFSET 0']
```

**Comment by barbequesauce** [comment]
Which nzbToWatcher3 script are you using?
