### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by jandreaucodes** [nosmokingbandit/Watcher3#313]
All of a sudden, my install won't launch from .plist. When trying to launch from command line, I get an error, seen below in the log.

** Commit: 9906c4a4416f7c669316e1bc9ba3d84f09875c64
** Operating System: macOS 10.15.6
** Python Version [python -V]: 3.8.2
** What happened: Tried to restart after a reboot and Watcher3 errors.
** Logs:
If logs contain information you do not wish to share with the world you may email them to `watchernzb@gmail.com`. Include the issue number in the subject line of the message.
```
Alfred@Pennyworth Watcher3 % /usr/local/bin/fdautil exec /usr/bin/python3 watcher.py --daemon
Connected to database sqlite:////Applications/Watcher3/userdata/watcher.sqlite
Config file found, merging any new options.
Clearing Mako cache.
Traceback (most recent call last):
  File "/Applications/Watcher3/lib/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/Applications/Watcher3/lib/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/Applications/Watcher3/lib/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "watcher.py", line 139, in <module>
    root = cherrypy.tree.mount(App(), '{}/'.format(core.URL_BASE), 'core/conf_app.ini')
  File "/Applications/Watcher3/lib/cherrypy/_cptree.py", line 226, in mount
    app.merge(config)
  File "/Applications/Watcher3/lib/cherrypy/_cptree.py", line 100, in merge
    _cpconfig.merge(self.config, config)
  File "/Applications/Watcher3/lib/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/Applications/Watcher3/lib/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/Applications/Watcher3/lib/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/Applications/Watcher3/lib/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ("Config error in section: '/', option: 'tools.auth.on', value: 'True'. Config values must be valid Python.", 'TypeError', ("unrepr does not recognize 'Constant'",))
```

**Comment by jandreaucodes** [comment]
Just updated to commit 2e33a970a6e0c4354705ec8dd0d9ab29de281073

Still seeing the same issue.

**Comment by frustin** [comment]
same, but on QNAP linux
** Python Version [python -V]: 3.9.0

```
[/share/CACHEDEV1_DATA/.qpkg/Watcher3/watcher] # /etc/init.d/owatcher3.sh restart
= (OWatcher3) is not active
= (OWatcher3) is not active
* updating (OWatcher3): OK
* starting (OWatcher3): failed!
= result: 1
= startup messages: 'Userdata directory exists, continuing.
Connected to database sqlite:////share/CACHEDEV1_DATA/.qpkg/OWatcher3/config/watcher.sqlite
Config file found, merging any new options.
Clearing Mako cache.
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/watcher.py", line 140, in <module>
    root = cherrypy.tree.mount(App(), '{}/'.format(core.URL_BASE), 'core/conf_app.ini')
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/_cptree.py", line 226, in mount
    app.merge(config)
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/_cptree.py", line 100, in merge
    _cpconfig.merge(self.config, config)
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/share/CACHEDEV1_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ("Config error in section: '/', option: 'tools.auth.on', value: 'True'. Config values must be valid Python.", 'TypeError', ("unrepr does not recognize 'Constant'",))'
```

**Comment by vestor** [comment]
Correct solution to this is:
sudo apt-get remove python3-cherrypy3
sudo pip3 install cherrypy
