### ISSUE TITLE
Deluge script error

### ISSUE THREAD

**Issue by ItsMeMike** [nosmokingbandit/Watcher3#4]
Follow up from [this](https://www.reddit.com/r/watcher/comments/5ynien/windows_deluge_not_executing_script/)

Batch file executes the python script now, but still outputs an error.
```
[WARNING ] 17:55:40 core:132 [execute] command 'C:\Watcher3\scripts\deluge.bat' failed with exit code 1
[WARNING ] 17:55:40 core:136 [execute] stderr: Traceback (most recent call last):

  File "C:\Watcher3\scripts\\deluge.py", line 49, in <module>

    response = json.loads(urllib.request.urlopen(request, timeout=600).read())

  File "C:\Python36\lib\urllib\request.py", line 223, in urlopen

    return opener.open(url, data, timeout)

  File "C:\Python36\lib\urllib\request.py", line 524, in open

    req = meth(req)

  File "C:\Python36\lib\urllib\request.py", line 1248, in do_request_

    raise TypeError(msg)

TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
```

**Comment by nosmokingbandit** [comment]
Hey, progress!

Get the script from 9e2a90cecdd81c5e0d34be0b0734679306dc639f and give it a whirl.

Thanks for being so patient. Python 3's string handling is still a little weird to me, but I'm getting the hang of it. Python 2 wasn't easier, just different and I know it much better.

Anyway, let me know what happens.

**Comment by ItsMeMike** [comment]
> Thanks for being so patient. 
Absolutely :) I want Watcher to succeed, since it is already better than every other solution out there.

Anyways, progress indeed! The request now reaches Watcher, however something fishy is still happening.
```
INFO 2017-03-30 09:21:40,309 core.postprocessing.POST: #################################
INFO 2017-03-30 09:21:40,309 core.postprocessing.POST: Post-processing request received.
INFO 2017-03-30 09:21:40,309 core.postprocessing.POST: #################################
INFO 2017-03-30 09:21:40,309 core.postprocessing.get_movie_file: Finding movie file.
INFO 2017-03-30 09:21:40,640 core.postprocessing.get_movie_file: Post-processing file C:\Users\MikeR\Downloads\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv.
INFO 2017-03-30 09:21:40,641 core.postprocessing.POST: Parsing release name for information.
INFO 2017-03-30 09:21:40,641 core.library.parse_filename: Parsing C:\Users\MikeR\Downloads\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv for movie information.
INFO 2017-03-30 09:21:40,655 core.library.parse_filename: Found {'year': 2014, 'resolution': '1080p', 'quality': 'BluRay', 'codec': 'x264', 'audio': 'DTS', 'group': 'PRoDJi.mkv', 'container': 'mkv', 'title': 'Gone Girl'} in filename.
INFO 2017-03-30 09:21:40,655 core.postprocessing.POST: Gathering release information.
INFO 2017-03-30 09:21:40,655 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-03-30 09:21:40,656 core.sqldb.get_single_search_result: Retrieving search result details for f41ee445a13569bb33d31bdbfc769f65b44f5ab8.
INFO 2017-03-30 09:21:40,661 core.postprocessing.get_movie_info: Guid not found.
INFO 2017-03-30 09:21:40,661 core.postprocessing.get_movie_info: Searching local database for downloadid.
INFO 2017-03-30 09:21:40,661 core.sqldb.get_single_search_result: Retrieving search result details for f41ee445a13569bb33d31bdbfc769f65b44f5ab8.
INFO 2017-03-30 09:21:40,662 core.postprocessing.get_movie_info: Unable to find local data for release. Attempting to get info from file.
INFO 2017-03-30 09:21:40,662 core.library.get_metadata: Gathering metada for C:\Users\MikeR\Downloads\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv.
INFO 2017-03-30 09:21:40,662 core.library.parse_filename: Parsing C:\Users\MikeR\Downloads\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv for movie information.
INFO 2017-03-30 09:21:40,663 core.library.parse_filename: Found {'year': 2014, 'resolution': '1080p', 'quality': 'BluRay', 'codec': 'x264', 'audio': 'DTS', 'group': 'PRoDJi.mkv', 'container': 'mkv', 'title': 'Gone Girl'} in filename.
INFO 2017-03-30 09:21:40,692 core.movieinfo._search_title: Searching TMDB https://api.themoviedb.org/3/search/movie?page=1&include_adult=false&query=gone+girl&year=2014
DEBUG 2017-03-30 09:21:40,710 lib.requests.packages.urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.themoviedb.org
DEBUG 2017-03-30 09:21:41,814 lib.requests.packages.urllib3.connectionpool._make_request: https://api.themoviedb.org:443 "GET /3/search/movie?page=1&include_adult=false&query=gone+girl&year=2014&api_key=APIKEY HTTP/1.1" 200 570
DEBUG 2017-03-30 09:21:41,817 lib.requests.packages.urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.themoviedb.org
DEBUG 2017-03-30 09:21:42,342 lib.requests.packages.urllib3.connectionpool._make_request: https://api.themoviedb.org:443 "GET /3/movie/210577?api_key=APIKEY HTTP/1.1" 200 769
INFO 2017-03-30 09:21:42,346 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-03-30 09:21:42,346 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-03-30 09:21:42,346 core.updatestatus.searchresults: Marking guid f41ee445a13569bb33d31bdbfc769f65b44f5ab8 as Finished.
INFO 2017-03-30 09:21:42,348 core.updatestatus.searchresults: Guid f41ee445a13569bb33d31bdbfc769f65b44f5ab8 not found in SEARCHRESULTS, attempting to create entry.
INFO 2017-03-30 09:21:42,349 core.scoreresults.score: Scoring 1 results.
INFO 2017-03-30 09:21:42,349 core.scoreresults.retention_check: Checking retention.
INFO 2017-03-30 09:21:42,349 core.scoreresults.retention_check: Keeping 1 results.
INFO 2017-03-30 09:21:42,349 core.scoreresults.score_sources: Filtering resolution and size requirements.
DEBUG 2017-03-30 09:21:42,349 core.scoreresults.score_sources: Gone Girl matches source BluRay-1080P, checking size.
DEBUG 2017-03-30 09:21:42,349 core.scoreresults.score_sources: Gone Girl is an import, skipping size check.
INFO 2017-03-30 09:21:42,349 core.scoreresults.score_sources: Keeping 1 results.
INFO 2017-03-30 09:21:42,349 core.scoreresults.fuzzy_title: Checking title match.
INFO 2017-03-30 09:21:42,349 core.scoreresults.fuzzy_title: Keeping 1 results.
INFO 2017-03-30 09:21:42,349 core.scoreresults.score_preferred: Scoring Preferred Words.
INFO 2017-03-30 09:21:42,349 core.scoreresults.score: Finished scoring search results.
INFO 2017-03-30 09:21:42,349 core.sqldb.write: Writing data to SEARCHRESULTS.
INFO 2017-03-30 09:21:42,370 core.updatestatus.markedresults: Guid f41ee445a13569bb33d31bdbfc769f65b44f5ab8 not found in MARKEDRESULTS, creating entry.
INFO 2017-03-30 09:21:42,370 core.sqldb.write: Writing data to MARKEDRESULTS.
INFO 2017-03-30 09:21:42,384 core.updatestatus.markedresults: Successfully created entry in MARKEDRESULTS for f41ee445a13569bb33d31bdbfc769f65b44f5ab8.
INFO 2017-03-30 09:21:42,385 core.postprocessing.complete: Setting MOVIE status.
INFO 2017-03-30 09:21:42,385 core.sqldb.get_movie_details: Retrieving details for tt2267998.
INFO 2017-03-30 09:21:42,385 core.sqldb.get_distinct: Getting distinct values for tt2267998 in SEARCHRESULTS
INFO 2017-03-30 09:21:42,386 core.updatestatus.movie_status: Setting MOVIES tt2267998 status to Finished.
INFO 2017-03-30 09:21:42,386 core.sqldb.update: Updating imdbid:tt2267998 to Finished in MOVIES.
INFO 2017-03-30 09:21:42,409 core.sqldb.update: Updating imdbid:tt2267998 to 2017-03-30 in MOVIES.
INFO 2017-03-30 09:21:42,424 core.sqldb.update: Updating imdbid:tt2267998 to None in MOVIES.
INFO 2017-03-30 09:21:42,447 core.postprocessing.renamer: Renaming Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv to Gone Girl (2014)[BluRay-1080P-PRoDJi.mkv.mkv
ERROR 2017-03-30 09:21:42,447 core.postprocessing.renamer: Renamer failed: Could not rename file.
Traceback (most recent call last):
  File "C:\Watcher3\core\postprocessing.py", line 673, in renamer
    os.rename(abs_path_old, abs_path_new)
FileNotFoundError: [WinError 3] Het systeem kan het opgegeven pad niet vinden: 'C_\\Users\\MikeR\\Downloads\\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv' -> 'C_\\Users\\MikeR\\Downloads\\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\\Gone Girl (2014)[BluRay-1080P-PRoDJi.mkv.mkv'
INFO 2017-03-30 09:21:42,732 core.postprocessing.mover: Moving C_\Users\MikeR\Downloads\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv to D:\Films\
ERROR 2017-03-30 09:21:42,733 core.postprocessing.mover: Mover failed: Could not move file.
Traceback (most recent call last):
  File "C:\Python36\lib\shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] Het systeem kan het opgegeven pad niet vinden: 'C_\\Users\\MikeR\\Downloads\\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv' -> 'D:\\Films\\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Watcher3\core\postprocessing.py", line 798, in mover
    shutil.move(current_file_path, target_folder)
  File "C:\Python36\lib\shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "C:\Python36\lib\shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python36\lib\shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C_\\Users\\MikeR\\Downloads\\films/Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi\\Gone.Girl.2014.BluRay.1080p.DTS.x264-PRoDJi.mkv'
INFO 2017-03-30 09:21:42,742 core.sqldb.update: Updating imdbid:tt2267998 to None in MOVIES.
**ERROR 2017-03-30 09:21:42,754 cherrypy.error.1773845602992.error: [30/Mar/2017:09:21:42] HTTP 
Traceback (most recent call last):
  File "C:\Watcher3\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Watcher3\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Watcher3\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Watcher3\core\postprocessing.py", line 101, in POST
    response['data'].pop('backlog')
KeyError: 'backlog'
INFO 2017-03-30 09:21:42,756 cherrypy.error.1773845602992.error: [30/Mar/2017:09:21:42] HTTP 
Request Headers:
  Remote-Addr: ::1
  ACCEPT-ENCODING: identity
  HOST: localhost:8082
  USER-AGENT: Mozilla/5.0
  CONNECTION: close
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 292
```

Something weird seems to happen with the slashes/backslashes in the filename? Not sure though, this is above my knowledge, heh.

**Comment by nosmokingbandit** [comment]
I've removed your log. Email it to me and I'll take a look. I don't like logs with media information out in the open.

**Comment by ItsMeMike** [comment]
Cool, let me know if you need anything!

**Comment by nosmokingbandit** [comment]
2b2519b2e21d4853a4f64601469933fec9c9dc52 should take care of this.

Weird chain of events that led to this, but I've tested a few times and it seems to be ok.

**Comment by ItsMeMike** [comment]
Ah yes, file is being moved now with naming options.

- Create hardlink to enable seeding torrents.
Seems to be not working, but that might be Windows messing with hardlinking? Not sure. But it just moves the file.

**Comment by nosmokingbandit** [comment]
That is just how hardlinks work. They both point directly to the file's data on the disk, which doesn't work if the link is on a different disk.

Symbolic links work across disks, but I couldn't get it to work well and gave up. I think python 3 has much better support for that so I'll check into it.
