### ISSUE TITLE
Qbittorrent connector broken

### ISSUE THREAD

**Issue by BillVeusees** [nosmokingbandit/Watcher3#45]
Hello,

The connector to qbittorrent seems broken.

qbittorrent is running on the same server as Watcher on port 8080 with login password.

I can login to the Http interface of qbittorrent with password with local or external ip. I can go to the  source of a magnet by Watcher, enter it in QB HTTP interface and the download will start

When I try to setup the downloader on qbittorrent with either localhost, 127.0.0.1, 0.0.0.0, lan IP or external ip i only get a red warning box with no message provided.

Qbittorrent does not log any connection attempt or magnets.

The config.cfg takes parameters into account.

When i click on a torrent it says 'magnet send to qbittorrent' in green,

Here some relevant log

`ERROR 2017-05-12 12:03:28,875 core.downloaders.qbittorrent._get_download_dir: QBittorrent unable to get download dir.
Traceback (most recent call last):
  File "/home/alex/Medias/.apps/Watcher3/core/downloaders/qbittorrent.py", line 87, in _get_download_dir
    response = json.loads(Url.open(url, headers=headers).text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
INFO 2017-05-12 12:03:28,910 core.snatcher.snatch_torrent: Successfully sent Blood.Father.2016.BluRay.1080p.x264.DTS-HDChina[PRiME] to QBittorrent.
`

**Comment by BillVeusees** [comment]
OK i looked at the api doc on qbittorrent
and it seems that the connector is only compatible with qbittorrent v 3.2.0 +

The API is not the same in particular

> /json/ was replaced with /query/ in all the requests

queries starting with json reach with me.

One way would be to implement the old versions of the api, yet I  will start by trying to upgrade qbittorrent on raspbian by activating stretch debian repos

**Comment by BillVeusees** [comment]
ok for a rpi adding 

deb http://ftp.fr.debian.org/debian stretch main 

to sources.list allows to upgrade qbittorrent-nox with only a few more packages
