### ISSUE TITLE
ExtraTorrent search failed

### ISSUE THREAD

**Issue by theflu** [nosmokingbandit/Watcher3#50]
Failed while doing manual search

Error:
```
xml.etree.ElementTree.ParseError: mismatched tag: line 27, column 2
  File "<string>", line None
    parser.feed(text)
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1325, in XML
    tree = ET.fromstring(xml)
  File "/opt/Watcher3/core/providers/torrent.py", line 434, in parse
    return ExtraTorrent.parse(response, imdbid)
  File "/opt/Watcher3/core/providers/torrent.py", line 397, in search
Traceback (most recent call last):
ERROR 2017-05-31 10:22:24,535 core.providers.torrent.search: ExtraTorrent search failed.
```

**Comment by nosmokingbandit** [comment]
Extratorrents is dead.
https://en.wikipedia.org/wiki/ExtraTorrent

They've been removed from Watcher.
