### ISSUE TITLE
After adding from api, system doesnt fire a automatic search

### ISSUE THREAD

**Issue by PotatoQuality** [nosmokingbandit/Watcher3#62]
Since the last update i sawt hat when i request a movie in Ombi, Watcher3 will add it but doesn't fire a automatic search and grab.

Testing some other movies. evertime there is a line "UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7752: character maps to <undefined>"

Logs:
````
INFO 2017-06-11 00:49:42,428 core.api.addmovie: API request add movie imdb tt1637688
INFO 2017-06-11 00:49:42,428 core.movieinfo._search_imdbid: Searching TMDB https://api.themoviedb.org/3/find/tt1637688?language=en-US&external_source=imdb_id&append_to_response=alternative_titles,external_ids,release_dates
DEBUG 2017-06-11 00:49:42,850 core.sqldb.write: Writing data to MOVIES.
INFO 2017-06-11 00:49:42,866 core.library.save_poster: Grabbing poster for tt1637688.
INFO 2017-06-11 00:49:42,866 core.library.save_poster: Saving poster to static/images/posters/tt1637688.jpg
INFO 2017-06-11 00:49:42,881 core.library.save_poster: Poster saved to static/images/posters/tt1637688.jpg
DEBUG 2017-06-11 00:49:53,163 core.sqldb.get_user_movies: Retrieving list of user's movies.
ERROR 2017-06-11 00:50:00,725 cherrypy.error.85130352.error: [11/Jun/2017:00:50:00] HTTP 
Traceback (most recent call last):
  File "C:\watcher\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\watcher\core\ajax.py", line 462, in get_log_text
    log_text = ''.join(reversed(f.readlines()))
  File "C:\Python3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7752: character maps to <undefined>
INFO 2017-06-11 00:50:00,725 cherrypy.error.85130352.error: [11/Jun/2017:00:50:00] HTTP 
Request Headers:
  Remote-Addr: 192.168.0.93
  HOST: 192.168.0.12:9090
  CONNECTION: keep-alive
  ACCEPT: */*
  ORIGIN: http://192.168.0.12:9090
  X-REQUESTED-WITH: XMLHttpRequest
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
  REFERER: http://192.168.0.12:9090/settings/logs
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
  COOKIE: list_sort=status_sort; list_direction=asc; _ncfa=CgA6Heq9arDTJn92Ta2LCrV%2frRLg25s35jrgGc1vDFI%3d83F4TsKEjKqnRUAmquUBn%2bZya5S%2bG%2bz1F5oCTe1oVr%2bZIGAymdw8tZyro40sakog; session_id=478159d1e09f61b8a9c6329a72eab20190d3c519; _pk_id.1.753c=0c2bf893ddaad921.1495378917.19.1497120165.1497120069.; movie_sort_key=status_key; movie_layout=posters; movie_sort_direction=desc; Auth-Type=http; Auth-Token=n9lGTWSbOjK65gzn4odfUwmU4jo2NW9kHk84ryDsqFsR2NQC; session=3fd7cdc9e614f3161b62b60c3f85a99c7a1a10a3
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  Content-Length: 15
````

**Comment by nosmokingbandit** [comment]
In commit d4a413f083edfed65baf075021d735a6e80e23b9 I cleaned up the add/search/snatch chain, which probably fixed the source of this.

I just added tt1637688 via api request and everything worked fine for me. Can you confirm this on your end?

As far as the unicode error, am I remembering correctly that your system's language is set to Dutch?

**Comment by PotatoQuality** [comment]
@nosmokingbandit correct. looks working again. but have now other problems with the last commit.
If i search something, the system found results and score them, setting also the status to found but i got this:
![image](https://user-images.githubusercontent.com/2944704/27205338-7539ed20-5230-11e7-8951-1f1c990f5d71.png)

Nothing found yet. Next search sheduled for undefined

**Comment by nosmokingbandit** [comment]
Is it just that one movie or others as well?

I can't reproduce that, so send the your logs and I'll see what is going on.

`watchernzb@gmail.com`
