### ISSUE TITLE
errors when importing from directory

### ISSUE THREAD

**Issue by phynias** [nosmokingbandit/Watcher3#65]
i try and import from directory but nothing ever gets added and i get this in the logs

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 99-101: surrogates not allowed
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Watcher3/lib/cherrypy/wsgiserver/__init__.py", line 1592, in run
    conn.communicate()
  File "/usr/local/Watcher3/lib/cherrypy/wsgiserver/__init__.py", line 1406, in communicate
    req.respond()
  File "/usr/local/Watcher3/lib/cherrypy/wsgiserver/__init__.py", line 860, in respond
    self.server.gateway(self).respond()
  File "/usr/local/Watcher3/lib/cherrypy/wsgiserver/__init__.py", line 2333, in respond
    for chunk in filter(None, response):
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 177, in __next__
    return self.trap(next, self.iter_response)
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 286, in __next__
    return next(self.iter_response)
  File "/usr/local/Watcher3/lib/cherrypy/lib/encoding.py", line 100, in encoder
    for chunk in body:
  File "/usr/local/Watcher3/core/ajax.py", line 553, in scan_library_directory
    metadata = self.metadata.from_file(path)
  File "/usr/local/Watcher3/core/library.py", line 419, in from_file
    logging.info('Gathering metadata for {}.'.format(filepath))
Message: 'Gathering metadata for /mnt/movies/Dude, Where\udce2\udc80\udc99s My Car/Dude, Where\udce2\udc80\udc99s My Car.mkv.'
Arguments: ()

**Comment by phynias** [comment]
ok i started watcher in daemon mode and the logs are now different.


now i get this for everything.

INFO 2017-06-11 14:10:57,693 core.library.from_file: Gathering metadata for /mnt/movies/Pretty in Pink/Pretty in Pink.avi.
INFO 2017-06-11 14:10:57,693 core.library.parse_filename: Parsing /mnt/movies/Pretty in Pink/Pretty in Pink.avi for movie information.
INFO 2017-06-11 14:10:57,693 core.library.parse_filename: Parsing filename doesn't look accurate. Parsing parent folder name.
INFO 2017-06-11 14:10:57,693 core.library.parse_filename: Found {'title': 'Pretty in Pink'} in parent folder.
INFO 2017-06-11 14:10:57,698 core.movieinfo._search_title: Searching TMDB https://api.themoviedb.org/3/search/movie?page=1&include_adult=false&query=pretty+in+pink
INFO 2017-06-11 14:10:58,422 core.ajax.scan_library_directory: Resolution/Source unknown for import Pretty in Pink

**Comment by kaibosh** [comment]
Those info messages indicate that it cannot determine the resolution/source information based on either the file or directory name. So it's likely to add with the default settings. Does that not happen?

**Comment by phynias** [comment]
it doesn't add anything. scans everything and nothing is ever added.

**Comment by nosmokingbandit** [comment]
Take another crack at it after fcd129e0a3c9cb6cdc4caf8c4e1fdc727fcd54ac.

The importer was stripping all whitespace rather than leading/trailing whitespace so the folder name was being converted to "PrettyInPink", which doesn't exist.

**Comment by phynias** [comment]
ok i don't get the same messages anymore. it looks like it is working. i get message like this for everything it finds:

INFO 2017-06-18 00:08:20,517 core.library.from_file: Gathering metadata for /mnt/movies/Back In Time/Back In Time.mkv.
INFO 2017-06-18 00:08:20,517 core.library.parse_filename: Parsing /mnt/movies/Back In Time/Back In Time.mkv for movie information.
INFO 2017-06-18 00:08:20,517 core.library.parse_filename: Parsing filename doesn't look accurate. Parsing parent folder name.
INFO 2017-06-18 00:08:20,517 core.library.parse_filename: Found {'title': 'Back In Time'} in parent folder.
INFO 2017-06-18 00:08:20,541 core.movieinfo._search_title: Searching TMDB https://api.themoviedb.org/3/search/movie?page=1&include_adult=false&query=back+in+time

INFO 2017-06-18 00:08:21,259 core.ajax.scan_library_directory: All data found for import Back in Time


but then nothing is showing up.

**Comment by nosmokingbandit** [comment]
I can't tell anything from that tiny log window. After those log entries you should get a list in your browser where you can review movies before adding. I'll need the logs after you click `Import Library` to see what is going on.

**Comment by chromerobv** [comment]
Browser window comes back with nothing just the import library button. I'll get more if the log for you shortly

**Comment by phynias** [comment]
i ran another import every scan was like the one i posted above.
then after i clicked the "Import Library" button i get this in the log



INFO 2017-06-19 19:19:20,820 core.searchresults.score: Scoring 0 results.
INFO 2017-06-19 19:19:20,821 core.searchresults.retention_check: Checking retention.
INFO 2017-06-19 19:19:20,821 core.searchresults.retention_check: Keeping 0 results.
INFO 2017-06-19 19:19:20,821 core.searchresults.seed_check: Checking torrent seeds.
INFO 2017-06-19 19:19:20,821 core.searchresults.seed_check: Keeping 0 results.
INFO 2017-06-19 19:19:20,821 core.searchresults.score_sources: Filtering resolution and size requirements.
INFO 2017-06-19 19:19:20,821 core.searchresults.score_sources: Keeping 0 results.
INFO 2017-06-19 19:19:20,821 core.searchresults.fuzzy_title: Checking title match.
INFO 2017-06-19 19:19:20,821 core.searchresults.fuzzy_title: Keeping 0 results.
INFO 2017-06-19 19:19:20,821 core.searchresults.score_preferred: Scoring Preferred Words.
INFO 2017-06-19 19:19:20,821 core.searchresults.score: Finished scoring search results.

fyi here are screen shots of the browser during each part.
no lists or anything just a button.
http://imgur.com/a/sjbP7

**Comment by nosmokingbandit** [comment]
Send me the full log.

`watchernzb@gmail.com`

**Comment by nosmokingbandit** [comment]
I'm leaving this open but I want to publicly post my findings so far. Luckily I have very patient users who don't mind helping me troubleshoot these things, so we eventually narrowed it down.

Certain AntiVirus programs (BitDefender in this particular case) will strip http headers and add their own. Most of the time this isn't a problem, when when executing long tasks such as an import (or any task in Watcher that shows a progress bar) the browser communicates with the server in chunks. This can't happen if the headers aren't preserved.

The only way around this that I know of is using websockets for the browser<->server connection. This would also require a pretty large rewrite of the frontend code, which I don't want to do again. At least not right now.

So if you are having a similar problem and came across this issue, try disabling your AV and see what happens. I can guarantee there is nothing nefarious going on and you don't need to be alarmed, but Watcher is 100% open source so you can check for yourself if you'd like.

I'm still looking for a better answer to this, but I'm afraid there might not be one.
