### ISSUE TITLE
got a traceback every hour

### ISSUE THREAD

**Issue by PotatoQuality** [nosmokingbandit/Watcher3#71]
not sure what is going on but i got this one every hour:

Exception in thread Thread-87:
Traceback (most recent call last):
  File "C:\Python3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python3\lib\threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "C:\watcher\core\cp_plugins\taskscheduler.py", line 122, in task
    self.func()
  File "C:\watcher\core\searcher.py", line 106, in search_all
    self.snatcher.grab_all()
  File "C:\watcher\core\snatcher.py", line 61, in grab_all
    if finished_date_obj + keepsearchingdelta >= today:
TypeError: can't compare datetime.datetime to datetime.date

**Comment by nosmokingbandit** [comment]
79c64f687ad7bc89fe69be9fbb6f545fee64c3c5 Should clear this up.

Let me know either way.

**Comment by PotatoQuality** [comment]
@nosmokingbandit got a new one:

Exception in thread Thread-22:
Traceback (most recent call last):
  File "C:\Python3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python3\lib\threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "C:\watcher\core\cp_plugins\taskscheduler.py", line 160, in _task
    self.task()
  File "C:\watcher\core\searcher.py", line 155, in search_all
    rss_movies = self._get_rss_movies(movies)
  File "C:\watcher\core\searcher.py", line 440, in _get_rss_movies
    finished_date_obj = datetime.datetime.strptime(i['finished_date'], '%Y-%m-%d').date()
TypeError: strptime() argument 1 must be str, not None

**Comment by nosmokingbandit** [comment]
Not 100% sure how a Finished movie doesn't get a finished_date, but 0c04c13435a507d5d22b2a7875c5843a895515ef will take care of Watcher choking when this happens.

Probably from a directory import movie, but its hard to tell. I made sure directory imports get a finished_date as well.

**Comment by PotatoQuality** [comment]
@nosmokingbandit  problem is back :(

Exception in thread Thread-42:
Traceback (most recent call last):
  File "C:\Python3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python3\lib\threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "C:\watcher\core\cp_plugins\taskscheduler.py", line 160, in _task
    self.task()
  File "C:\watcher\core\searcher.py", line 155, in search_all
    rss_movies = self._get_rss_movies(movies)
  File "C:\watcher\core\searcher.py", line 443, in _get_rss_movies
    if finished_date_obj + keepsearchingdelta >= today:
TypeError: can't compare datetime.datetime to datetime.date

**Comment by nosmokingbandit** [comment]
I swear I went through and fixed all of that. My memory must be failing me. That would actually explain a lot.
870ae998d21c392edf9d842e03ed3e687da51f36 should get you back in working order.

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.
