### ISSUE TITLE
AttributeError: 'SQL' object has no attribute 'convert_names'

### ISSUE THREAD

**Issue by ludwigbacklund** [nosmokingbandit/Watcher3#75]
Getting this error when trying to start watcher, not sure why it's happening now. Worked fine before I went on vacation a few weeks ago.

```
$ python3 watcher.py
C:\Watcher3\lib\fuzzywuzzy\fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Opening SQL DB.
Traceback (most recent call last):
  File "C:\Watcher3\core\sqldb.py", line 83, in __init__
    self.update_tables()
  File "C:\Watcher3\core\sqldb.py", line 587, in update_tables
    if table in self.convert_names.keys():
AttributeError: 'SQL' object has no attribute 'convert_names'
Connected to database sqlite:///C:\Watcher3\watcher.sqlite
Database update required. This may take some time.
Backing up database to C:\Watcher3\db.
Modifying tables.
Modifying table MOVIES
Traceback (most recent call last):
  File "watcher.py", line 65, in <module>
    core.sql = sqldb.SQL()
  File "C:\Watcher3\core\sqldb.py", line 83, in __init__
    self.update_tables()
  File "C:\Watcher3\core\sqldb.py", line 587, in update_tables
    if table in self.convert_names.keys():
AttributeError: 'SQL' object has no attribute 'convert_names'

```

**Comment by nosmokingbandit** [comment]
4800fc62ebb543afef963b84d1293d9d2fb3cdbb Fixes this. You may need to run `git pull` in the watcher dir (or redownload the zip if you use that instead, just remember to run the back up and restore), but then everything should be back to normal.

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.
