### ISSUE TITLE
Error 500 on Status Page

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#82]
Watcher Version: Latest, linuxserver/watcher docker container but updated via app.
Manage page works ok.

[09/Jul/2017:15:48:11] "GET / HTTP/1.1" 200 2740 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
[09/Jul/2017:15:48:11] HTTP 
Traceback (most recent call last):
  File "/app/watcher/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/app/watcher/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 11 supplied.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/watcher/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/app/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/watcher/core/ajax.py", line 54, in library
    return core.sql.get_user_movies(sort_key, sort_direction.upper(), limit, offset)
  File "/app/watcher/core/sqldb.py", line 292, in get_user_movies
    result = self.execute(command)
  File "/app/watcher/core/sqldb.py", line 135, in execute
    result = self.engine.execute(*command)
  File "/app/watcher/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/app/watcher/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/app/watcher/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/app/watcher/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/app/watcher/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/app/watcher/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/watcher/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/app/watcher/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/app/watcher/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Incorrect number of bindings supplied. The current statement uses 0, and there are 11 supplied. [SQL: 'SELECT * FROM MOVIES ORDER BY CASE WHEN status = "Waiting" THEN 1\n                               WHEN status = "Wanted" THEN 2\n                               WHEN status = "Found" THEN 3\n                               WHEN status = "Snatched" THEN 4\n                               WHEN status = "Finished" THEN 5\n                          END\n                        DESC'] [parameters: (',', ' ', 't', 'i', 't', 'l', 'e', ' ', 'A', 'S', 'C')]
172.19.0.4 - - [09/Jul/2017:15:48:11] "POST /ajax/library HTTP/1.1" 500 3824 "https://watcher" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
[09/Jul/2017:15:48:11] HTTP

**Comment by oskarszoon** [comment]
Same issue for me. I have it set to automatically install updates, so unsure when this started happening.

**Comment by liam-uk** [comment]
Same issue for me. I just updated using the built-in updater. Running on Synology.

**Comment by nosmokingbandit** [comment]
I'm looking into this now, but it seems to be triggered by the sort being set to Year or Status. Setting it to Title will make it usable until I figure out why it isn't working.

**Comment by nosmokingbandit** [comment]
Fixed in bf2b1218be56098e0ae275657957501be22b86db

This is the result of a bugfix from a day or two ago. Usually fixing one bug makes several more show up, so if this is all the damage I caused I'll consider it a win.

**Comment by oskarszoon** [comment]
@nosmokingbandit It happens :) , thanks for the quick fix

**Comment by jaketame** [comment]
Looks to be resolved. Thanks.
