### ISSUE TITLE
ImportError: cannot import name 'searcher'

### ISSUE THREAD

**Issue by SevenNine** [nosmokingbandit/Watcher3#9]
Ubuntu 14.04.1
Python 3.4.3

Fresh git pull.  Unable to start.

```
user@ubuntu /o/watcher> python3 /opt/watcher/watcher.py --daemon
Traceback (most recent call last):
  File "/opt/watcher/watcher.py", line 13, in <module>
    from core import api, config, postprocessing, scheduler, sqldb
  File "/opt/watcher/core/api.py", line 6, in <module>
    from core import ajax, sqldb, poster
  File "/opt/watcher/core/ajax.py", line 9, in <module>
    from core import config, library, plugins, poster, scoreresults, searcher, snatcher, sqldb, updatestatus, version
  File "/opt/watcher/core/searcher.py", line 5, in <module>
    from core import scoreresults, snatcher, sqldb, updatestatus, proxy
  File "/opt/watcher/core/snatcher.py", line 5, in <module>
    from core import plugins, sqldb, updatestatus
  File "/opt/watcher/core/updatestatus.py", line 3, in <module>
    from core import sqldb, library, scoreresults, searcher
ImportError: cannot import name 'searcher'
```

searcher.py is in core/

```
user@ubuntu /o/watcher> ls core
ajax.py          conf_api.ini     conf_postprocessing.ini  __init__.py      plugins.py         __pycache__/     snatcher.py
api.py           conf_app.ini     cp_plugins/              library.py       poster.py          rss/             sqldb.py
app.py           conf_auth.ini    downloaders/             log.py           postprocessing.py  scheduler.py     updatestatus.py
auth.py          conf_global.ini  favicon.ico              movieinfo.py     providers/         scoreresults.py  version.py
base_config.cfg  config.py        helpers.py               notification.py  proxy.py           searcher.py
```

**Comment by nosmokingbandit** [comment]
This is weird. Circular importing should prevent the script from starting no matter what, but for some reason my copy kept working fine.

Either way, 52d5055c4ce8a853f7f8aa2b9f2b82362202931d should take care of it.

**Comment by SevenNine** [comment]
It did.  Thanks.
