### ISSUE TITLE
importing via Plex

### ISSUE THREAD

**Issue by phynias** [nosmokingbandit/Watcher3#95]
when i try and import with Plex it fails, when i first ran it, it imported several movies then died. when i try and run it again it comes back with variants of this.

DEBUG 2017-07-17 14:59:40,227 core.sqldb.get_user_movies: Retrieving list of user's movies.
INFO 2017-07-17 15:00:15,444 core.movieinfo._search_imdbid: Searching TMDB https://api.themoviedb.org/3/find/tt1491614?language=en-US&external_source=imdb_id&append_to_response=alternative_titles,external_ids,release_dates
ERROR 2017-07-17 15:00:15,852 cherrypy.error.34519283864.error: [17/Jul/2017:15:00:15]  Traceback (most recent call last):
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 285, in __next__
    return next(self.iter_response)
  File "/usr/local/Watcher3/lib/cherrypy/lib/encoding.py", line 100, in encoder
    for chunk in body:
  File "/usr/local/Watcher3/core/ajax.py", line 984, in import_plex_csv
    response = core.manage.add_movie(movie)
  File "/usr/local/Watcher3/core/library.py", line 716, in add_movie
    tmdbid = movie['id']
KeyError: 'id'

another odd thing i noticed is that it will put "undefined" where the tmdb is should be and it isn't editable. so i uncheck those ones, or else it errors out on those.

**Comment by phynias** [comment]
looks like it fixes the undefined problem but not the major problem preventing it from importing the movies. i still get 


ERROR 2017-07-19 17:00:18,683 core.ajax.import_plex_csv: Unable to find Pete Holmes: Faces and Sounds on TMDB.
DEBUG 2017-07-19 17:00:18,683 core.ajax.import_plex_csv: {'tmdbid': '426488', 'title': 'Pete Holmes: Faces and Sounds', 'year': '2016', 'added_date': '2017-07-19', 'finished_date': '2017-07-19', 'audiocodec': 'ac3', 'resolution': 'BluRay-720P', 'size': 1392846902, 'file': '/media/!Video/Movies/Pete Holmes Facesand Sounds/Pete Holmes Faces andSounds.mkv', 'finished_file': '/mnt/movies/Pete Holmes Facesand Sounds/Pete Holmes Faces andSounds.mkv'}
INFO 2017-07-19 17:00:18,683 core.movieinfo._search_imdbid: Searching TMDB https://api.themoviedb.org/3/find/tt1491614?language=en-US&external_source=imdb_id&append_to_response=alternative_titles,external_ids,release_dates
ERROR 2017-07-19 17:00:19,904 cherrypy.error.34510437344.error: [19/Jul/2017:17:00:19]  Traceback (most recent call last):
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 285, in __next__
    return next(self.iter_response)
  File "/usr/local/Watcher3/lib/cherrypy/lib/encoding.py", line 100, in encoder
    for chunk in body:
  File "/usr/local/Watcher3/core/ajax.py", line 988, in import_plex_csv
    response = core.manage.add_movie(movie)
  File "/usr/local/Watcher3/core/library.py", line 716, in add_movie
    tmdbid = movie['id']
KeyError: 'id'

ERROR 2017-07-19 17:00:19,905 cherrypy.error.34510437344.error: [19/Jul/2017:17:00:19]
Traceback (most recent call last):
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 214, in trap
    self.start_response(s, h, _sys.exc_info())
  File "/usr/local/Watcher3/lib/cheroot/wsgi.py", line 149, in start_response
    six.reraise(*exc_info)
  File "/usr/local/Watcher3/lib/six.py", line 686, in reraise
    raise value
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 285, in __next__
    return next(self.iter_response)
  File "/usr/local/Watcher3/lib/cherrypy/lib/encoding.py", line 100, in encoder
    for chunk in body:
  File "/usr/local/Watcher3/core/ajax.py", line 988, in import_plex_csv
    response = core.manage.add_movie(movie)
  File "/usr/local/Watcher3/core/library.py", line 716, in add_movie
    tmdbid = movie['id']
KeyError: 'id'
ERROR 2017-07-19 17:00:19,989 cherrypy.error.error: [19/Jul/2017:17:00:19] ENGINE KeyError('id',)
Traceback (most recent call last):
  File "/usr/local/Watcher3/lib/cheroot/server.py", line 1075, in communicate
    req.respond()
  File "/usr/local/Watcher3/lib/cheroot/server.py", line 902, in respond
    self.server.gateway(self).respond()
  File "/usr/local/Watcher3/lib/cheroot/wsgi.py", line 127, in respond
    for chunk in filter(None, response):
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 177, in __next__
    return self.trap(next, self.iter_response)
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 214, in trap
    self.start_response(s, h, _sys.exc_info())
  File "/usr/local/Watcher3/lib/cheroot/wsgi.py", line 149, in start_response
    six.reraise(*exc_info)
  File "/usr/local/Watcher3/lib/six.py", line 686, in reraise
    raise value
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "/usr/local/Watcher3/lib/cherrypy/_cpwsgi.py", line 285, in __next__
    return next(self.iter_response)
  File "/usr/local/Watcher3/lib/cherrypy/lib/encoding.py", line 100, in encoder
    for chunk in body:
  File "/usr/local/Watcher3/core/ajax.py", line 988, in import_plex_csv
    response = core.manage.add_movie(movie)
  File "/usr/local/Watcher3/core/library.py", line 716, in add_movie
    tmdbid = movie['id']
KeyError: 'id'

**Comment by nosmokingbandit** [comment]
Would you mind emailing me your csv file? I'm not able to reproduce this on my side and having your csv will help me find exactly where the problem is. The only possibly sensitive info in the csv is file paths -- everything else is just movie metadata.

`watchernzb@gmail.com`

**Comment by nosmokingbandit** [comment]
4a92f7b86fc4e2f4d563df0073521ee6263239be should get this working as expected.

The problem that in at least one movie the TheMovieDatabase ID# wasn't correct, or even valid at all. I assumed that if Plex had a link to TheMovieDatabase that it would be valid. This commit assumes nothing.

**Comment by phynias** [comment]
looks good now. thanks!
