### ISSUE TITLE
The weird Trakt api key obfuscation isn't working

### ISSUE THREAD

**Issue by mattbailey** [nosmokingbandit/Watcher3#99]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/redacted/src/Watcher3/core/cp_plugins/taskscheduler.py", line 179, in _task
    self.task()
  File "/Users/redacted/src/Watcher3/core/trakt.py", line 36, in trakt_sync
    movies += [i for i in self.get_list(k, min_score=min_score, length=length) if i not in movies]
  File "/Users/redacted/src/Watcher3/core/trakt.py", line 67, in get_list
    'trakt-api-key': Comparisons._k(b'trakt')
  File "/Users/redacted/src/Watcher3/core/helpers.py", line 198, in _k
    return bd(rc(d[k])).decode('ascii')  # looooooooooooooooool
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/base64.py", line 205, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding
```

**Comment by nosmokingbandit** [comment]
Fixed in b82fb9989afb468fd4bc7fefa606b03be4443efe. Tuples, man. They'll get you every time.
